PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
 TCTRL_/SIE/HR_IDP_VF0T               CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
 MODULE FILL_SUBSTFLDS.
 MODULE READ_TEXT.                                     "XFT 27-08-2001
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /SIE/HR_IDP_VF0T-IDENT.
    FIELD /SIE/HR_IDP_VF0T-GRKEY.
    FIELD /SIE/HR_IDP_VF0T-PARENT.
    FIELD /SIE/HR_IDP_VF0T-SORTN.
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /SIE/HR_IDP_VF0T-GRKEY.
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
*
   FIELD VIM_MARKED MODULE ADMIN_INCLUDE.
*
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
