PROCESS BEFORE OUTPUT.
 MODULE INIT_5000.
 MODULE READ_IFCID.
 MODULE STATUS_5000.
 LOOP AT GT_INTERFACES
         INTO /SIE/HR_IDP_MONITOR_GD
         WITH CONTROL CTRL_VALIDITY
         CURSOR CTRL_VALIDITY-CURRENT_LINE.
     MODULE SET_SCREEN.
     MODULE LINES.
 ENDLOOP.
 MODULE CHECK_EMPTY.
*
PROCESS AFTER INPUT.
 MODULE EXIT_COMMAND AT EXIT-COMMAND.
 MODULE COPY_OK_CODE.
 LOOP AT GT_INTERFACES.
 ENDLOOP.
 MODULE USER_COMMAND_5000.
