PROCESS BEFORE OUTPUT.
 MODULE DETAIL_INIT.
 MODULE ENABLE_GROUP1_001.                         " XFT 27-08-2001
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
  FIELD /SIE/HR_IDP_VF1S-GRKEY.
  FIELD /SIE/HR_IDP_VF1S-KZVSR.
  FIELD /SIE/HR_IDP_VF1S-SLNAM.
  FIELD /SIE/HR_IDP_VF1S-FELDNAME.
  FIELD /SIE/HR_IDP_VF1S-SORTN.                    " XFT 08-10-2001
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
  MODULE COMPLETE_/SIE/HR_IDP_VF1S ON CHAIN-REQUEST.
 ENDCHAIN.
 CHAIN.
  FIELD /SIE/HR_IDP_VF1S-FELDNAME.
  MODULE DETAIL_PAI.
 ENDCHAIN.
 MODULE EXIT_CODE_ADM.                                " XFT 27-08-2001




















