FUNCTION-POOL /SIE/HR_IDP_DIALOGE.         "MESSAGE-ID ..

TABLES: /SIE/HR_IDP_ADM.

DATA: OKCODE LIKE SY-UCOMM.


* Konstanten
CONSTANTS: LINE_LENGTH TYPE I VALUE 80.

* Tabellen für den Datenaustausch
TYPES: BEGIN OF MYTABLE_LINE,
         LINE(LINE_LENGTH) TYPE C,
       END OF MYTABLE_LINE.

* Referenzen
DATA: EDITOR TYPE REF TO C_TEXTEDIT_CONTROL.

* globale Variablen
DATA: GL_TEXTLINES     TYPE TABLE OF MYTABLE_LINE,
      GL_READONLY      TYPE C,
      MYTABLE          TYPE TABLE OF MYTABLE_LINE,

      REPID            LIKE SY-REPID,
      GL_TITLE         LIKE TTXIT-TDTEXT,
      GL_HEADER        LIKE THEAD.

DEFINE DEFINE_TABLE.
  DATA: BEGIN OF &1 OCCURS &3.
          INCLUDE STRUCTURE &2.
  DATA: END OF &1.
END-OF-DEFINITION.

DEFINE_TABLE LINESB POPUPTEXT 10.
DEFINE_TABLE LINESH POPUPTEXT 10.

TABLES: SPOP.

DATA: NCOL LIKE SY-CUCOL.
DATA  INFOFLAG0.
DATA  LAST_SHOW_LINE LIKE SY-STEPL.
DATA: TEXT1(80), TEXT2(80), TEXT3(80), TEXT4(80), TEXT5(80),
      TEXT6(80), TEXT7(80), TEXT8(40), TEXT9(40).
