*----------------------------------------------------------------------*
*   INCLUDE /SIE/HR_IDP_SEL_INTERVAL                                   *
*----------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK EINSTELLUNG WITH FRAME TITLE TEXT-E01
                 NO INTERVALS.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-001 FOR FIELD LOOPC.
SELECTION-SCREEN POSITION 33.
*
PARAMETERS  LOOPC   LIKE RSEUMOD-TBMAXSEL DEFAULT 200.
SELECTION-SCREEN END  OF LINE.
SELECTION-SCREEN END OF BLOCK EINSTELLUNG.
