REPORT   /SIE/HR_IDP_FELDER MESSAGE-ID /SIE/HR_IDP_MESSAGES.

INCLUDE <LINE>.
INCLUDE /SIE/HR_IDP_TYPES.

TABLES: /SIE/HR_IDP_F1
      , /SIE/HR_IDP_F1T
      , /SIE/HR_IDP_F1LT
      ,  /SIE/HR_IDP_FIELDSEARCH
      , SSCRFIELDS
      .

DATA: G_INFTY TYPE STANDARD TABLE OF /SIE/HR_IDP_FIELDSEARCH
    , G_LGART TYPE STANDARD TABLE OF /SIE/HR_IDP_FIELDSEARCH
    , G_GEBIL TYPE STANDARD TABLE OF /SIE/HR_IDP_FIELDSEARCH
    , G_KTO TYPE  STANDARD TABLE OF /SIE/HR_IDP_FIELDSEARCH
    , G_DATA TYPE STANDARD TABLE OF /SIE/HR_IDP_FIELDSEARCH
    , G_WA TYPE /SIE/HR_IDP_FIELDSEARCH
    .

TYPE-POOLS: SLIS.

* Listaufbereitung
DATA:   GT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV.
DATA:   GT_OUTTAB LIKE SIMLISTRUC OCCURS 0 WITH HEADER LINE.
DATA:   G_TABNAME TYPE SLIS_TABNAME VALUE 'G_DATA'.
DATA:   G_REPID LIKE SY-REPID.
DATA    G_STATUS TYPE SLIS_FORMNAME VALUE 'STANDARD_02'.
DATA    GS_LAYOUT TYPE SLIS_LAYOUT_ALV.
DATA    G_USER_COMMAND TYPE SLIS_FORMNAME VALUE 'USER_COMMAND'.
DATA    G_SAVE(1) TYPE C.
DATA    G_VARIANT LIKE DISVARIANT.
