PROCESS BEFORE OUTPUT.
 MODULE SET_PF_STATUS_700.
 MODULE INIT.                               " Wird von allen aufgerufen
 MODULE INIT_0700.
* MODULE ifcid_read.

PROCESS AFTER INPUT.
 MODULE USER_COMMAND_0700.
 MODULE EXIT_COMMAND_0700 AT EXIT-COMMAND.
 CHAIN.
   FIELD G_700_SATZART.
   FIELD /SIE/HR_IDP_S1SA-RECTY.
   FIELD /SIE/HR_IDP_S1SA-DBAHD.
   FIELD /SIE/HR_IDP_S1SA-DBAOC.
   FIELD /SIE/HR_IDP_S1SA-INFTY.
   FIELD /SIE/HR_IDP_S1SA-SUBTY.
   FIELD /SIE/HR_IDP_S1SA-KZSRN.
   FIELD /SIE/HR_IDP_S1SA-KZSPN.
   MODULE CHECK_0700 ON CHAIN-REQUEST.
 ENDCHAIN.

* ....HIER KOMMEN DIE ÄNDERUNGEN
 CHAIN.
   FIELD: G_700_SATZART.
*   module check_input_700 on chain-input.
    MODULE CHECK_INPUT_700 ON CHAIN-REQUEST.
  ENDCHAIN.
 MODULE OK_CODE_700.
















