PROCESS BEFORE OUTPUT.
 MODULE INIT_4001.
 MODULE SET_STATUS.
 CALL SUBSCREEN SUBSCR_TITLE INCLUDING '/SIE/HR_IDP_IFC' C_TITL_SDYN.
 MODULE READ_S1VN.
 MODULE READ_S1R.
 MODULE READ_S1LT.
 MODULE READ_S1F.
 MODULE READ_S1DF.
 MODULE READ_1001.
 MODULE READ_4001.
 CALL SUBSCREEN SUBSCR_MATRIX INCLUDING '/SIE/HR_IDP_IFC' C_MTRX_SDYN.
*
PROCESS AFTER INPUT.
 MODULE EXIT_COMMAND AT EXIT-COMMAND.
 MODULE COPY_OK_CODE.
 CALL SUBSCREEN SUBSCR_TITLE.
 CALL SUBSCREEN SUBSCR_MATRIX.
 MODULE WRITE_4001.
 MODULE HANDLE_OKCODES_4001.


