FUNCTION-POOL /SIE/HR_IDP_GENERATOR.        "MESSAGE-ID ..


TYPE-POOLS: RSDS.

INCLUDE /SIE/HR_IDP_TYPES.
  TABLES: /SIE/HR_IDP_F1,
          /SIE/HR_IDP_F1S,
          /SIE/HR_IDP_C1,
          /SIE/HR_FUBA_KAT,
          FUPARAREF,
          TRDIR,
          DD40L,
          T599B,
          T599R,
          VARI.


DATA:
  G_REPID      TYPE PROGRAMM,
  G_VARIANT    TYPE VARIANT,
  G_DELIMITER  TYPE /SIE/HR_IDP_DELIMITER,
  G_FIXFORMAT  TYPE /SIE/HR_IDP_FIX_FORMAT,
  G_DELTA      TYPE /SIE/HR_IDP_DELTAKZ,
  G_FILEINTERN TYPE FILEINTERN,
  G_FILEEXTERN TYPE FILEEXTERN,
  G_FILENAME   TYPE TEXT256,
  G_FILENAME_SD TYPE TEXT256,
  CODE         TYPE /SIE/HR_IDP_TT_CODING,
  G_TEMPLATE   TYPE /SIE/HR_IDP_TT_CODING,
  IT_INFOTYPES TYPE TABLE OF INFTY,
  IT_SATZART   TYPE TABLE OF /SIE/HR_IDP_SATZARTEN,
  IT_SA_INFTY  TYPE TABLE OF /SIE/HR_IDP_SA_INFOTYPES,
  IT_FELDER    TYPE TABLE OF /SIE/HR_IDP_FIELDS,
  IT_FILTER    TYPE TABLE OF /SIE/HR_IDP_FILTER,           "SIE002
  IT_MONTHBACK TYPE TABLE OF /SIE/HR_IDP_MONTHS_BACK,
  IT_RD_TABS   TYPE TABLE OF /SIE/HR_IDP_TABNAME,
  G_VERSION    TYPE /SIE/HR_IDP_VERS_NR,
  G_INDBW8, G_INDBW14, G_INDBW15, G_INDBW52, G_IT24.
