FUNCTION /SIE/HR_IDP_IFC_COPY.
*"----------------------------------------------------------------------
*"*"Lokale Schnittstelle:
*"  IMPORTING
*"     VALUE(OLD_INTERFACE) TYPE  /SIE/HR_IDP_IFC_DB
*"     VALUE(NEW_ID) TYPE  /SIE/HR_IDP_INTERFACE_ID
*"     VALUE(NEW_VERSION) TYPE  /SIE/HR_IDP_VERS_NR
*"     VALUE(ACT_VERSION) TYPE  /SIE/HR_IDP_VERS_NR OPTIONAL
*"     VALUE(DBSEL) TYPE  /SIE/HR_IDP_DB_SEL
*"  EXPORTING
*"     VALUE(NEW_INTERFACE) TYPE  /SIE/HR_IDP_IFC_DB
*"----------------------------------------------------------------------


  DATA: WA_S1R TYPE /SIE/HR_IDP_S1R
      , WA_S1PG TYPE /SIE/HR_IDP_S1PG
      , WA_S1PS TYPE /SIE/HR_IDP_S1PS
      , WA_S1VT TYPE /SIE/HR_IDP_S1VT
      , WA_S1LT TYPE /SIE/HR_IDP_S1LT
      , WA_S1F TYPE /SIE/HR_IDP_S1F
      , WA_S1SA TYPE /SIE/HR_IDP_S1SA
      , WA_S1DL TYPE /SIE/HR_IDP_S1DL
      , RC LIKE SY-SUBRC
      .

  RC = 0.
  PERFORM CHECK_AUTHORITY USING SY-TCODE
                             C_DISPLAY
                             OLD_INTERFACE-S1-AUTH_CLASS
                             OLD_INTERFACE-S1-IFCID
                             SPACE
                        CHANGING RC.

  PERFORM CHECK_AUTHORITY USING SY-TCODE
                             C_CREATE
                             OLD_INTERFACE-S1-AUTH_CLASS
                             NEW_ID
                             SPACE
                        CHANGING RC.

* Die Schnittstelle so wie sie ist kopieren.
  NEW_INTERFACE = OLD_INTERFACE.

* Die neuen Namen (ID) und Versionszahl übernehmen
  NEW_INTERFACE-S1-IFCID = NEW_ID.
  NEW_INTERFACE-S1-ACT_VERS_NR = ACT_VERSION.
  NEW_INTERFACE-S1-NEW_VERSION = YES.
  NEW_INTERFACE-S1T-IFCID = NEW_ID.

  IF DBSEL-S1PR = YES.
    NEW_INTERFACE-S1PR-IFCID = NEW_ID.
    NEW_INTERFACE-S1PR-VRSNR = NEW_VERSION.
  ENDIF.

* Alle Versionsabhängige Tabelle ändern.
  IF DBSEL-S1DF = YES.
* Generierte Programme bekommen automatisch eine neue Kennung
    IF NEW_INTERFACE-S1DF-GNRTD = 'X'.
      CLEAR NEW_INTERFACE-S1DF-PROGR.
      CLEAR NEW_INTERFACE-S1DF-VARIA.
    ENDIF.
    NEW_INTERFACE-S1DF-IFCID = NEW_ID.
    NEW_INTERFACE-S1DF-VRSNR = NEW_VERSION.
  ENDIF.

  IF DBSEL-S1F = YES.
    LOOP AT NEW_INTERFACE-S1F INTO WA_S1F.
      CLEAR WA_S1F.
      WA_S1F-IFCID = NEW_ID.
      WA_S1F-VRSNR = NEW_VERSION.
      WA_S1F-TROLE = SY-TABIX + 5.
      MODIFY NEW_INTERFACE-S1F FROM WA_S1F INDEX SY-TABIX.
    ENDLOOP.
  ENDIF.

  CLEAR NEW_INTERFACE-S1VN.
  NEW_INTERFACE-S1VN-VRSNR = NEW_VERSION.
  NEW_INTERFACE-S1VN-IFCID = NEW_ID.

  IF DBSEL-S1R = YES.
    LOOP AT NEW_INTERFACE-S1R INTO WA_S1R.
      WA_S1R-IFCID = NEW_ID.
      WA_S1R-VRSNR = NEW_VERSION.
      MODIFY NEW_INTERFACE-S1R FROM WA_S1R INDEX SY-TABIX.
    ENDLOOP.
  ENDIF.

*SIE001_BEG
*  IF DBSEL-S1PG = YES.
*    LOOP AT NEW_INTERFACE-S1R INTO WA_S1PG.
*      WA_S1PG-IFCID = NEW_ID.
*      WA_S1PG-VRSNR = NEW_VERSION.
*      MODIFY NEW_INTERFACE-S1R FROM WA_S1PG INDEX SY-TABIX.
*    ENDLOOP.
*  ENDIF.

  IF DBSEL-S1PG = YES.
    LOOP AT NEW_INTERFACE-S1PG INTO WA_S1PG.
      WA_S1PG-IFCID = NEW_ID.
      WA_S1PG-VRSNR = NEW_VERSION.
      MODIFY NEW_INTERFACE-S1PG FROM WA_S1PG INDEX SY-TABIX.
    ENDLOOP.
  ENDIF.

  IF DBSEL-S1PS = YES.
    LOOP AT NEW_INTERFACE-S1PS INTO WA_S1PS.
      WA_S1PS-IFCID = NEW_ID.
      WA_S1PS-VRSNR = NEW_VERSION.
      MODIFY NEW_INTERFACE-S1PS FROM WA_S1PS INDEX SY-TABIX.
    ENDLOOP.
  ENDIF.
*SIE001_END

  IF DBSEL-S1VT = YES.
    LOOP AT NEW_INTERFACE-S1VT INTO WA_S1VT.
      WA_S1VT-IFCID = NEW_ID.
      WA_S1VT-VRSNR = NEW_VERSION.
      MODIFY NEW_INTERFACE-S1VT FROM WA_S1VT INDEX SY-TABIX.
    ENDLOOP.
  ENDIF.

  IF DBSEL-S1LT = YES.
    LOOP AT NEW_INTERFACE-S1LT INTO WA_S1LT.
      WA_S1LT-IFCID = NEW_ID.
      MODIFY NEW_INTERFACE-S1LT FROM WA_S1LT INDEX SY-TABIX.
    ENDLOOP.
  ENDIF.

  IF DBSEL-S1SA = YES.
    LOOP AT NEW_INTERFACE-S1SA INTO WA_S1SA.
      WA_S1SA-IFCID = NEW_ID.
      WA_S1SA-VRSNR = NEW_VERSION.
      MODIFY NEW_INTERFACE-S1SA FROM WA_S1SA INDEX SY-TABIX.
    ENDLOOP.
  ENDIF.

  IF DBSEL-S1PG = YES.
    LOOP AT NEW_INTERFACE-S1PG INTO WA_S1PG.
      WA_S1PG-IFCID = NEW_ID.
      WA_S1PG-VRSNR = NEW_VERSION.
      MODIFY NEW_INTERFACE-S1PG FROM WA_S1PG INDEX SY-TABIX.
    ENDLOOP.
  ENDIF.

  IF DBSEL-S1DL = YES.
    NEW_INTERFACE-S1DL-IFCID = NEW_ID.
    NEW_INTERFACE-S1DL-VRSNR = NEW_VERSION.
  ENDIF.

  IF DBSEL-S1PC = YES.
    NEW_INTERFACE-S1PC-IFCID = NEW_ID.
    NEW_INTERFACE-S1PC-VRSNR = NEW_VERSION.
  ENDIF.

ENDFUNCTION.
