FUNCTION-POOL /SIE/HR_IDP_TYPES MESSAGE-ID /SIE/HR_IDP_MESSAGES.

TABLES: /SIE/HR_IDP_C1
      , /SIE/HR_IDP_F1
      , T500L
      , DD40L
      , /SIE/HR_FUBA_KAT
      , FUPARAREF
      .

  CONSTANTS: FIELD_TYPE TYPE C VALUE ','.

  RANGES: G_ITAB_TYPES FOR FIELD_TYPE.
