PROCESS BEFORE OUTPUT.
 MODULE DETAIL_INIT.
 MODULE READ_TEXT.                                     "XFT 27-08-2001
* module show_admin.                                    "XFT 27-08-2001
 MODULE ENABLE_GROUP1_001.                             "XFT 27-08-2001
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
  FIELD /SIE/HR_IDP_VF0T-PARENT.
  FIELD /SIE/HR_IDP_VF0T-SORTN.
  FIELD /SIE/HR_IDP_VF0T-IDENT.
  FIELD /SIE/HR_IDP_VF0T-GRKEY.
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 ENDCHAIN.
 CHAIN.
  FIELD /SIE/HR_IDP_VF0T-GRKEY.
  MODULE DETAIL_PAI.
 ENDCHAIN.
 MODULE EXIT_CODE_ADM.                                  "XFT 27-08-2001
