PROCESS BEFORE OUTPUT.
  MODULE INIT_3000.
  MODULE READ_3000.
  CALL SUBSCREEN SUBSCR_RELE INCLUDING '/SIE/HR_IDP_IFC' C_RELE_SDYN.
  MODULE SET_STATUS.
  MODULE READ_S1LT.
  MODULE STATUS_3000.
*
PROCESS AFTER INPUT.
  MODULE EXIT_2000 AT EXIT-COMMAND.
  CHAIN.
   FIELD /SIE/HR_IDP_S1-IFCID.
  ENDCHAIN.
  MODULE COPY_OK_CODE.
  CALL SUBSCREEN SUBSCR_RELE.
  MODULE USER_COMMAND_3000.





