***INCLUDE /SIE/HR_IDP_XML_TYPES .

TYPES: T_EVENT(15) TYPE C
     , BEGIN OF S_XML_EVENT
     ,   EVENT TYPE T_EVENT
     ,   CALLBACK_FORM(15) TYPE C
     , END OF S_XML_EVENT
     , T_XML_EVENT TYPE STANDARD TABLE OF S_XML_EVENT
     .

TYPES: BEGIN OF S_XML_FILE
     ,  LINE(1000)
     , END OF S_XML_FILE
     , T_XML_FILE TYPE STANDARD TABLE OF S_XML_FILE
     .

TYPES: T_TAGNAME(15) TYPE C
     , T_VALUE(132) TYPE C
     .
