*----------------------------------------------------------------------*
*   INCLUDE /SIE/HR_IDP_FELDER_SEL                                     *
*----------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK STANDARD WITH FRAME TITLE TEXT-S01
                                         NO INTERVALS.
SELECT-OPTIONS: P_KEY1  FOR /SIE/HR_IDP_F1-FELDNAME.
SELECT-OPTIONS: P_XTEXT FOR /SIE/HR_IDP_F1T-IDENT.
SELECTION-SCREEN END OF BLOCK STANDARD.

SELECTION-SCREEN BEGIN OF BLOCK MORE WITH FRAME TITLE TEXT-S02
                                     NO INTERVALS.

SELECT-OPTIONS: P_CRNAM FOR /SIE/HR_IDP_F1-CR_UNAME
                        MATCHCODE OBJECT USER_ADDR.
SELECT-OPTIONS: P_DATUM FOR /SIE/HR_IDP_F1-DATUM.
SELECT-OPTIONS: P_UNAME FOR /SIE/HR_IDP_F1-UNAME
                        MATCHCODE OBJECT USER_ADDR.

SELECT-OPTIONS P_TEXT FOR /SIE/HR_IDP_F1LT-TLINE.
SELECT-OPTIONS P_TYPE  FOR /SIE/HR_IDP_FIELDSEARCH-DATATYPE.
SELECT-OPTIONS P_LEN  FOR /SIE/HR_IDP_FIELDSEARCH-LENG.

* Infotypen
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS P_INFTY AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN COMMENT 4(10) TEXT-R04 FOR FIELD P_INFTY.
SELECTION-SCREEN END OF LINE.
SELECT-OPTIONS P_INFOT FOR /SIE/HR_IDP_F1-INFTY.
SELECT-OPTIONS P_SUBTY FOR /SIE/HR_IDP_F1-SUBTY.
SELECT-OPTIONS P_IFELD FOR /SIE/HR_IDP_F1-INFTYFELD.
SELECT-OPTIONS P_KVNAME FOR /SIE/HR_IDP_F1-KONVNAME.

* Lohnarten
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS P_LGART AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN COMMENT 4(10) TEXT-R06 FOR FIELD P_LGART.
SELECTION-SCREEN END OF LINE.
SELECT-OPTIONS P_RTLGRT FOR /SIE/HR_IDP_F1-RTLGART.
SELECT-OPTIONS P_RTKZ FOR /SIE/HR_IDP_F1-RTKZ.

* Gebildete Begriffe
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS P_GEBIL AS CHECKBOX DEFAULT ' '.
SELECTION-SCREEN COMMENT 4(20) TEXT-R05 FOR FIELD P_GEBIL.
SELECTION-SCREEN END OF LINE.

* Clusterdaten
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS P_KTO AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN COMMENT 4(10) TEXT-R03 FOR FIELD P_INFTY.
SELECTION-SCREEN END OF LINE.

SELECT-OPTIONS P_ACLTAB FOR /SIE/HR_IDP_F1-ACLTAB.
SELECT-OPTIONS P_ACLFLD FOR /SIE/HR_IDP_F1-ACLFELD.
*
SELECTION-SCREEN END OF BLOCK MORE.
*
INCLUDE /SIE/HR_IDP_SEL_INTERVAL.

* Definition Selektionsbild für F4-Popup
* Alle Selektionen
*selection-screen begin of screen 100 as window.
* selection-screen include blocks standard.
* selection-screen include blocks more.
* selection-screen include blocks einstellung.
*selection-screen end   of screen 100.
