PROCESS BEFORE OUTPUT.
 MODULE DETAIL_INIT.
 MODULE ENABLE_GROUP1_001.                         " XFT 17-10-2001
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
  FIELD /SIE/HR_IDP_VC1T-KONVLENG.
  FIELD /SIE/HR_IDP_VC1T-KONVPARA.
  FIELD /SIE/HR_IDP_VC1T-KONVLIST.
  FIELD /SIE/HR_IDP_VC1T-KONVFLAG.
  FIELD /SIE/HR_IDP_VC1T-IDENT.
  FIELD /SIE/HR_IDP_VC1T-FUBANAM.
  FIELD /SIE/HR_IDP_VC1T-KONVNAM.
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 ENDCHAIN.
 CHAIN.
  FIELD /SIE/HR_IDP_VC1T-KONVNAM.
  MODULE DETAIL_PAI.
 ENDCHAIN.

  MODULE EXIT_CODE_ADM.                                " XFT 17-10-2001
