FUNCTION-POOL /SIE/HR_IDP_UC4 MESSAGE-ID /SIE/HR_IDP_MESSAGES.

TYPE-POOLS: SABC.

TABLES: /SIE/HR_IDP_A1.

INCLUDE /SIE/HR_IDP_TYPES.

DATA: G_TEMPLATE TYPE /SIE/HR_IDP_TT_SD
    , CODE TYPE /SIE/HR_IDP_TT_SD
    .
