PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
 TCTRL_/SIE/HR_IDP_VS0T               CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
*   module docu_button.                         " XFT 27-08-2001
 ENDLOOP.
 MODULE SHOW_ADM_BUTTON.                               " XFT 27-08-2001
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /SIE/HR_IDP_VS0T-IDENT.
    FIELD /SIE/HR_IDP_VS0T-AUTH_CLASS.
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /SIE/HR_IDP_VS0T-AUTH_CLASS.
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
     MODULE EXIT_CODE_ADM.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
 MODULE ADMIN_SHOW.           " XFT 27-08-2001


















