PROCESS BEFORE OUTPUT.
 MODULE INIT_2510.
 MODULE READ_2510.
 MODULE STATUS_2510.
*
PROCESS AFTER INPUT.
  MODULE EXIT_2510 AT EXIT-COMMAND.
  MODULE COPY_OK_CODE.
  CHAIN.
    FIELD: /SIE/HR_IDP_A1-IFCID
         , /SIE/HR_IDP_A1-VRSNR
         , /SIE/HR_IDP_A1-HOSTN
         , /SIE/HR_IDP_A1-TCPIP
         , /SIE/HR_IDP_A1-PORTN
         , /SIE/HR_IDP_A1-TRFAD
         , /SIE/HR_IDP_A1-EMSUC
         , /SIE/HR_IDP_A1-EMERR
         , /SIE/HR_IDP_A1-UC4NM
         .
 ENDCHAIN.

 FIELD /SIE/HR_IDP_A1-UC4NM MODULE CHECK_UC4NM_2510.  " User Name
 FIELD /SIE/HR_IDP_A1-TCPIP MODULE CHECK_TCPIP_2510.  " IP Adress
 FIELD /SIE/HR_IDP_A1-PORTN MODULE CHECK_PORTN_2510.  " Port number
 FIELD /SIE/HR_IDP_A1-TRFAD MODULE CHECK_TRFAD_2510.  " Transferadm.

* No more modifications after this line!
 MODULE USER_COMMAND_2510.
















