PROCESS BEFORE OUTPUT.
   MODULE INIT_0100.
   MODULE READ_S1.
   MODULE READ_S1T.
   MODULE READ_S1F.
   MODULE FILL_DATA_100.
   MODULE MODIFY_SCREEN_100.
*
PROCESS AFTER INPUT.
   CHAIN.
     FIELD: /SIE/HR_IDP_HEAD-IFCID
          , /SIE/HR_IDP_HEAD-IDENT.
   ENDCHAIN.
   FIELD /SIE/HR_IDP_HEAD-IFCID MODULE CHECK_CHANGE.
   FIELD /SIE/HR_IDP_HEAD-IFCID MODULE CHECK_EXISTENCE ON REQUEST.
   FIELD /SIE/HR_IDP_HEAD-IFCID MODULE CHECK_NAME.
   MODULE COPY_DATA_100.
*
