PROCESS BEFORE OUTPUT.
 MODULE STATUS_0500.
 MODULE INIT_0500.
 MODULE READ_S1VN_DATA.
 MODULE FILL_RELEASED.
 LOOP AT  G_RELEASED
     INTO /SIE/HR_IDP_RELEASED
     WITH CONTROL TC_RELEASED
     CURSOR TC_RELEASED-CURRENT_LINE.
   MODULE FILL_SELECTION_0500.
   MODULE LINES.
 ENDLOOP.

*
PROCESS AFTER INPUT.
 LOOP AT G_RELEASED.
*  module transfer_0500.
 ENDLOOP.
 MODULE USER_COMMAND_0500.

