PROCESS BEFORE OUTPUT.
 MODULE STATUS_0400.
 MODULE FILL_MATRIX.
 LOOP AT G_ITAB_S1R
      INTO /SIE/HR_IDP_IFC_ROLES
      WITH CONTROL TC_MATRIX
      CURSOR TC_MATRIX-CURRENT_LINE.
   MODULE FILL_0400.
   MODULE MODIFY_SCREEN.
   MODULE LINES.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE INIT_G_MATRIX.
 LOOP AT G_ITAB_S1R.
 CHAIN.
  FIELD /SIE/HR_IDP_IFC_ROLES-PERNR.
  FIELD /SIE/HR_IDP_IFC_ROLES-ORGEH.
  FIELD /SIE/HR_IDP_IFC_ROLES-USERN.
  FIELD /SIE/HR_IDP_IFC_ROLES-EMAIL.
  MODULE WRITE_MATRIX ON CHAIN-REQUEST.
 ENDCHAIN.
 FIELD /SIE/HR_IDP_IFC_ROLES-USERN MODULE CHECK_UNAME.
 ENDLOOP.
 MODULE USER_COMMAND_0400.
*
PROCESS ON VALUE-REQUEST.
 FIELD /SIE/HR_IDP_IFC_ROLES-ORGEH MODULE ORGEH_HELP.




