PROCESS BEFORE OUTPUT.
 MODULE INIT_VERSION.
 MODULE READ_S1VN_DATA.
 MODULE FILL_VERSION_DATA.
 LOOP AT  G_T_VERS_0100
      INTO /SIE/HR_IDP_IFC_VERSIONS
      WITH CONTROL TC_VERS
      CURSOR TC_MATRIX-CURRENT_LINE.
  MODULE FILL_VERSION.
  MODULE LINES.
 ENDLOOP.

*
PROCESS AFTER INPUT.
 MODULE INIT_PAI_0100.
 LOOP AT G_T_VERS_0100.
  MODULE EXTRACT_USERDATA.
 ENDLOOP.
 MODULE SET_VERSION.

 MODULE CATCH_OKCODE_PICK.
