*----------------------------------------------------------------------*
*   INCLUDE /SIE/HR_IDP_IFC_FIND_SEL                                   *
*----------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK STANDARD WITH FRAME TITLE TEXT-S01
                                         NO INTERVALS.
SELECT-OPTIONS: P_KEY1  FOR /SIE/HR_IDP_S1-IFCID.
SELECT-OPTIONS: P_XTEXT FOR /SIE/HR_IDP_S1T-IDENT.
SELECT-OPTIONS P_TEXT FOR /SIE/HR_IDP_S1LT-TLINE.
PARAMETERS: P_RELEAS AS CHECKBOX DEFAULT 'X'.
PARAMETERS: P_INWORK AS CHECKBOX DEFAULT 'X'.
PARAMETERS: P_HISTO AS CHECKBOX.
SELECTION-SCREEN END OF BLOCK STANDARD.

SELECTION-SCREEN BEGIN OF BLOCK FIELDS WITH FRAME TITLE TEXT-S03
                                         NO INTERVALS.
SELECT-OPTIONS: P_FIELD FOR /SIE/HR_IDP_F1-FELDNAME.
*select-options p_type  for /sie/hr_idp_fieldsearch-datatype.
*select-options p_len  for /sie/hr_idp_fieldsearch-leng.
select-options: p_REFER for /SIE/HR_IDP_S1-IFCID.          "SIE001

SELECTION-SCREEN END OF BLOCK FIELDS.

SELECTION-SCREEN BEGIN OF BLOCK MORE WITH FRAME TITLE TEXT-S02
                                     NO INTERVALS.
SELECT-OPTIONS: P_CRNAM FOR /SIE/HR_IDP_S1-CR_UNAME
                        MATCHCODE OBJECT USER_ADDR.
SELECT-OPTIONS: P_DATUM FOR /SIE/HR_IDP_S1-DATUM.
SELECT-OPTIONS: P_UNAME FOR /SIE/HR_IDP_S1-UNAME
                        MATCHCODE OBJECT USER_ADDR.
SELECTION-SCREEN END OF BLOCK MORE.

INCLUDE /SIE/HR_IDP_SEL_INTERVAL.
