PROCESS BEFORE OUTPUT.
 MODULE DETAIL_INIT.
 MODULE ENABLE_GROUP1_001.                         " XFT 27-08-2001
*module enable_group4_001.                         " XFT 29-08-2001
 MODULE DISABLE_CONV.                              " XFT 30-08-2001
 MODULE READ_QFIELDS.                              " XFT 27-08-2001
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
  FIELD /SIE/HR_IDP_VF1T-RTKZ.
  FIELD /SIE/HR_IDP_VF1T-RTLGART.
  FIELD /SIE/HR_IDP_VF1T-ACLFELD.
  FIELD /SIE/HR_IDP_VF1T-ACLTAB.
  FIELD /SIE/HR_IDP_VF1T-BEGRIFF.
  FIELD /SIE/HR_IDP_VF1T-IDENT.
  FIELD /SIE/HR_IDP_VF1T-KONVNAME.
  FIELD /SIE/HR_IDP_VF1T-KONVSTRG.
  FIELD /SIE/HR_IDP_VF1T-INFTYFELD.
  FIELD /SIE/HR_IDP_VF1T-SUBTY.
  FIELD /SIE/HR_IDP_VF1T-INFTY.
  FIELD /SIE/HR_IDP_VF1T-DPFTYPE.
  FIELD /SIE/HR_IDP_VF1T-SORTN.
  FIELD /SIE/HR_IDP_VF1T-GRKEY.
  FIELD /SIE/HR_IDP_VF1T-FELDNAME.
  FIELD /SIE/HR_IDP_VF1T-AGGREGATE.
  FIELD /SIE/HR_IDP_VF1T-SINGULAR.
  FIELD /SIE/HR_IDP_VF1T-KZHDFT.
  FIELD /SIE/HR_IDP_VF1T-FL_MODIF.
  FIELD /SIE/HR_IDP_VF1T-STRU_VAL.
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 ENDCHAIN.

 CHAIN.
  FIELD /SIE/HR_IDP_VF1T-FELDNAME.
  MODULE DETAIL_PAI.
 ENDCHAIN.

  CHAIN.                                              " XFT 30-08-2001
   FIELD /SIE/HR_IDP_VF1T-KONVSTRG.                   " XFT 30-08-2001
   FIELD /SIE/HR_IDP_VF1T-KONVNAME.                   " XFT 30-08-2001
   MODULE CHECK_CONVERSION.                           " XFT 30-08-2001
  ENDCHAIN.
  CHAIN.
    FIELD /SIE/HR_IDP_VF1T-RTKZ.
    FIELD /SIE/HR_IDP_VF1T-RTLGART.
    FIELD /SIE/HR_IDP_VF1T-ACLFELD.
    FIELD /SIE/HR_IDP_VF1T-ACLTAB.
    FIELD /SIE/HR_IDP_VF1T-BEGRIFF.
    FIELD /SIE/HR_IDP_VF1T-INFTYFELD.
    FIELD /SIE/HR_IDP_VF1T-SUBTY.
    FIELD /SIE/HR_IDP_VF1T-INFTY.
    FIELD /SIE/HR_IDP_VF1T-DPFTYPE.
    FIELD /SIE/HR_IDP_VF1T-AGGREGATE.
    MODULE CHECK_CONSISTENCY ON CHAIN-REQUEST.
  ENDCHAIN.

  CHAIN.                                              " XFT 13-11-2001
    FIELD /SIE/HR_IDP_VF1T-RTKZ.                      " XFT 13-11-2001
    FIELD /SIE/HR_IDP_VF1T-AGGREGATE.                 " XFT 13-11-2001
    FIELD /SIE/HR_IDP_VF1T-DPFTYPE.                   " XFT 13-11-2001
    MODULE CHECK_AGGREGATE ON CHAIN-REQUEST.          " XFT 13-11-2001
  ENDCHAIN.                                           " XFT 13-11-2001

  CHAIN.                                              " XFT 30-08-2001
    FIELD /SIE/HR_IDP_VF1T-INFTY.                     " XFT 30-08-2001
    FIELD /SIE/HR_IDP_VF1T-INFTYFELD.                 " XFT 30-08-2001
    MODULE CHECK_INFTY ON CHAIN-REQUEST.              " XFT 30-08-2001
  ENDCHAIN.                                           " XFT 30-08-2001

  CHAIN.
  FIELD /SIE/HR_IDP_VF1T-FELDNAME.
  MODULE CHECK_FELDNAME ON CHAIN-REQUEST.             " XFT 30-08-2001
  ENDCHAIN.

  CHAIN.
  FIELD /SIE/HR_IDP_VF1T-FL_MODIF.
  FIELD /SIE/HR_IDP_VF1T-STRU_VAL.
  MODULE CHECK_MODIF ON CHAIN-REQUEST.
  ENDCHAIN.

  MODULE EXIT_CODE_ADM.                                " XFT 27-08-2001
  MODULE EXIT_CODE_LTXT.                               " XFT 27-08-2001

PROCESS ON VALUE-REQUEST.                              " XFT 27-08-2001
  FIELD /SIE/HR_IDP_VF1T-INFTYFELD MODULE INFTYFELD_F4." XFT 27-08-2001
