*----------------------------------------------------------------------*
*   INCLUDE /SIE/HR_IDP_STAT_SEL                                       *
*----------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK SEL WITH FRAME TITLE TEXT-S00.
SELECT-OPTIONS: SO_IFCID FOR /SIE/HR_IDP_S1-IFCID
              , SO_SEQNO FOR /SIE/HR_IDP_S1P-SEQNO
              .

SELECT-OPTIONS: SO_BEGDA FOR /SIE/HR_IDP_S1P-BEGDA DEFAULT SY-DATUM
              , SO_BEGUZ FOR /SIE/HR_IDP_S1P-BEGUZ DEFAULT
                '000000' TO '240000'.                       "#EC NOTEXT
.
SELECTION-SCREEN END OF BLOCK SEL.

SELECTION-SCREEN BEGIN OF BLOCK WSEL WITH FRAME TITLE TEXT-S02.
SELECT-OPTIONS: SO_JUPER FOR /SIE/HR_IDP_S1S-JUPER
              , SO_WERKS FOR /SIE/HR_IDP_S1S-WERKS
              , SO_BREIN FOR /SIE/HR_IDP_S1S-BREIN
              .
SELECTION-SCREEN END OF BLOCK WSEL.

SELECTION-SCREEN BEGIN OF BLOCK OPT WITH FRAME TITLE TEXT-S01.
PARAMETERS: P_S1P AS CHECKBOX DEFAULT YES
          , P_S1L AS CHECKBOX DEFAULT YES
          , P_S1S AS CHECKBOX DEFAULT YES
          .
SELECTION-SCREEN END OF BLOCK OPT.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR SO_JUPER-LOW.
  PERFORM F4_JUPER.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR SO_JUPER-HIGH.
  PERFORM F4_JUPER.
