PROCESS BEFORE OUTPUT.
 MODULE SET_TRAN_STATUS_1001.
 MODULE INIT.                               " Wird von allen aufgerufen
 MODULE SET_STATUS.                         " Wird von allen aufgerufen
 MODULE SET_DEFAULTS.
 CALL SUBSCREEN SUBSCR_TITLE INCLUDING '/SIE/HR_IDP_IFC' C_TITL_SDYN.
 MODULE READ_S1VN.
 MODULE READ_S1R.
 MODULE READ_S1LT.
 MODULE READ_S1F.
 MODULE READ_AUTH.
 CALL SUBSCREEN SUBSCR_MATRIX INCLUDING '/SIE/HR_IDP_IFC' C_MTRX_SDYN.
 MODULE READ_1001.
 MODULE MODIFY_SCREEN.
*
PROCESS AFTER INPUT.
 MODULE EXIT_COMMAND AT EXIT-COMMAND.       " Wird von allen aufgerufen
  CHAIN.
   FIELD: /SIE/HR_IDP_S1-VALID_FROM
       , /SIE/HR_IDP_S1-CUSTOMER
       , /SIE/HR_IDP_S1-AUTH_CLASS
       , /SIE/HR_IDP_S1-VALID_FROM
       , /SIE/HR_IDP_S1-VALID_TO
       , /SIE/HR_IDP_S1-ACT_VERS_NR
       , /SIE/HR_IDP_S1-NEW_VERSION
       .
 ENDCHAIN.
 MODULE COPY_OK_CODE.                       " Wird von allen aufgerufen
 CALL SUBSCREEN SUBSCR_TITLE.               " Wird von allen aufgerufen
 CALL SUBSCREEN SUBSCR_MATRIX.
 MODULE FILL_KEYS_1000.
 MODULE WRITE_1001.
 CHAIN.
  FIELD /SIE/HR_IDP_S1-VALID_FROM.
  FIELD /SIE/HR_IDP_S1-VALID_TO.
  MODULE CHECK_DATES ON CHAIN-REQUEST.
 ENDCHAIN.
 MODULE USER_COMMAND.                       " Wird von allen aufgerufen


