PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
 TCTRL_/SIE/HR_IDP_VC1T               CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
*    field /sie/hr_idp_vc1t-konvpara.
*    field /sie/hr_idp_vc1t-konvlist.
    FIELD /SIE/HR_IDP_VC1T-IDENT.
*    field /sie/hr_idp_vc1t-fubanam.
    FIELD /SIE/HR_IDP_VC1T-KONVNAM.
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /SIE/HR_IDP_VC1T-KONVNAM.
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
