*----------------------------------------------------------------------*
*   INCLUDE /SIE/HR_IDP_IFC_ALERT_SEL                                  *
*----------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK sel1 WITH FRAME TITLE text-s01.
SELECT-OPTIONS: so_ifcid FOR /sie/hr_idp_s1-ifcid.
PARAMETERS: p_only NO-DISPLAY.
SELECTION-SCREEN END OF BLOCK sel1.

SELECTION-SCREEN BEGIN OF BLOCK sel2 WITH FRAME TITLE text-s02.

PARAMETERS: val_date TYPE /sie/hr_idp_valid_to DEFAULT sy-datum
          , val_intv TYPE /sie/hr_idp_month_offset DEFAULT 2
          .
SELECTION-SCREEN END OF BLOCK sel2.

SELECTION-SCREEN BEGIN OF BLOCK sel3 WITH FRAME TITLE text-s03.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_01 AS CHECKBOX.
SELECTION-SCREEN COMMENT 3(27) text-p01 FOR FIELD p_01.
SELECTION-SCREEN POSITION 33.
PARAMETERS: r_01_to RADIOBUTTON GROUP r01.
SELECTION-SCREEN COMMENT 35(10) text-to0 FOR FIELD r_01_to.
SELECTION-SCREEN POSITION 45.
PARAMETERS: r_01_cc RADIOBUTTON GROUP r01.
SELECTION-SCREEN COMMENT 47(10) text-cc0 FOR FIELD r_01_cc.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_02 AS CHECKBOX.
SELECTION-SCREEN COMMENT 3(27) text-p02 FOR FIELD p_02.
SELECTION-SCREEN POSITION 33.
PARAMETERS: r_02_to RADIOBUTTON GROUP r02.
SELECTION-SCREEN COMMENT 35(10) text-to0 FOR FIELD r_02_to.
SELECTION-SCREEN POSITION 45.
PARAMETERS: r_02_cc RADIOBUTTON GROUP r02.
SELECTION-SCREEN COMMENT 47(10) text-cc0 FOR FIELD r_02_cc.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_03 AS CHECKBOX.
SELECTION-SCREEN COMMENT 3(27) text-p03 FOR FIELD p_03.
SELECTION-SCREEN POSITION 33.
PARAMETERS: r_03_to RADIOBUTTON GROUP r03.
SELECTION-SCREEN COMMENT 35(10) text-to0 FOR FIELD r_03_to.
SELECTION-SCREEN POSITION 45.
PARAMETERS: r_03_cc RADIOBUTTON GROUP r03.
SELECTION-SCREEN COMMENT 47(10) text-cc0 FOR FIELD r_03_cc.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_04 AS CHECKBOX.
SELECTION-SCREEN COMMENT 3(27) text-p04 FOR FIELD p_04.
SELECTION-SCREEN POSITION 33.
PARAMETERS: r_04_to RADIOBUTTON GROUP r04.
SELECTION-SCREEN COMMENT 35(10) text-to0 FOR FIELD r_04_to.
SELECTION-SCREEN POSITION 45.
PARAMETERS: r_04_cc RADIOBUTTON GROUP r04 DEFAULT 'X'.
SELECTION-SCREEN COMMENT 47(10) text-cc0 FOR FIELD r_04_cc.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_05 AS CHECKBOX.
SELECTION-SCREEN COMMENT 3(27) text-p05 FOR FIELD p_05.
SELECTION-SCREEN POSITION 33.
PARAMETERS: r_05_to RADIOBUTTON GROUP r05.
SELECTION-SCREEN COMMENT 35(10) text-to0 FOR FIELD r_05_to.
SELECTION-SCREEN POSITION 45.
PARAMETERS: r_05_cc RADIOBUTTON GROUP r05.
SELECTION-SCREEN COMMENT 47(10) text-cc0 FOR FIELD r_05_cc.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_06 AS CHECKBOX.
SELECTION-SCREEN COMMENT 3(27) text-p06 FOR FIELD p_06.
SELECTION-SCREEN POSITION 33.
PARAMETERS: r_06_to RADIOBUTTON GROUP r06.
SELECTION-SCREEN COMMENT 35(10) text-to0 FOR FIELD r_06_to.
SELECTION-SCREEN POSITION 45.
PARAMETERS: r_06_cc RADIOBUTTON GROUP r06.
SELECTION-SCREEN COMMENT 47(10) text-cc0 FOR FIELD r_06_cc.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_07 AS CHECKBOX.
SELECTION-SCREEN COMMENT 3(27) text-p07 FOR FIELD p_07.
SELECTION-SCREEN POSITION 33.
PARAMETERS: r_07_to RADIOBUTTON GROUP r07.
SELECTION-SCREEN COMMENT 35(10) text-to0 FOR FIELD r_07_to.
SELECTION-SCREEN POSITION 45.
PARAMETERS: r_07_cc RADIOBUTTON GROUP r07.
SELECTION-SCREEN COMMENT 47(10) text-cc0 FOR FIELD r_07_cc.
SELECTION-SCREEN END OF LINE.

PARAMETERS: von LIKE soextreci1-receiver,
            cc  LIKE soextreci1-receiver.
SELECTION-SCREEN END OF BLOCK sel3.

SELECTION-SCREEN BEGIN OF BLOCK sel5 WITH FRAME TITLE text-s05.
PARAMETERS: form LIKE thead-tdform
          , spras LIKE rstxd-tdspras DEFAULT sy-langu NO-DISPLAY
          .
PARAMETERS: p_screen AS CHECKBOX DEFAULT 'X'
          , p_email AS CHECKBOX DEFAULT space
          .
SELECTION-SCREEN END OF BLOCK sel5.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR form.
  PERFORM namerequest.
