PROCESS BEFORE OUTPUT.
 MODULE STATUS_5200.
 MODULE INIT_5200.
*
PROCESS AFTER INPUT.
  MODULE EXIT_COMMAND AT EXIT-COMMAND.
  MODULE COPY_OK_CODE.
 CHAIN.
   FIELD /SIE/HR_IDP_ROLES-R01.
   FIELD /SIE/HR_IDP_ROLES-R02.
   FIELD /SIE/HR_IDP_ROLES-R03.
   FIELD /SIE/HR_IDP_ROLES-R04.
   FIELD /SIE/HR_IDP_ROLES-R05.
   FIELD /SIE/HR_IDP_ROLES-R06.
   FIELD /SIE/HR_IDP_ROLES-R07.

   FIELD /SIE/HR_IDP_ROLES-R01_TO.
   FIELD /SIE/HR_IDP_ROLES-R02_TO.
   FIELD /SIE/HR_IDP_ROLES-R03_TO.
   FIELD /SIE/HR_IDP_ROLES-R04_TO.
   FIELD /SIE/HR_IDP_ROLES-R05_TO.
   FIELD /SIE/HR_IDP_ROLES-R06_TO.
   FIELD /SIE/HR_IDP_ROLES-R07_TO.

   FIELD /SIE/HR_IDP_ROLES-R01_CC.
   FIELD /SIE/HR_IDP_ROLES-R02_CC.
   FIELD /SIE/HR_IDP_ROLES-R03_CC.
   FIELD /SIE/HR_IDP_ROLES-R04_CC.
   FIELD /SIE/HR_IDP_ROLES-R05_CC.
   FIELD /SIE/HR_IDP_ROLES-R06_CC.
   FIELD /SIE/HR_IDP_ROLES-R07_CC.

   FIELD /SIE/HR_IDP_ROLES-CC.

 ENDCHAIN.
 MODULE USER_COMMAND_5200.





