PROCESS BEFORE OUTPUT.
 MODULE STATUS_0800.
*
PROCESS AFTER INPUT.
 MODULE EXIT_COMMAND_0800 AT EXIT-COMMAND.
 CHAIN.
   FIELD: /SIE/HR_IDP_S1F-LTEXT.
 ENDCHAIN.
 MODULE COPY_OK_CODE.
 MODULE USER_COMMAND_0800.
