PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
 TCTRL_/SIE/HR_IDP_VF1T               CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
*   field /sie/hr_idp_vf1t-aclfeld.
*   field /sie/hr_idp_vf1t-acltab.
*   field /sie/hr_idp_vf1t-begriff.
    FIELD /SIE/HR_IDP_VF1T-IDENT.
*   field /sie/hr_idp_vf1t-konvname.
*   field /sie/hr_idp_vf1t-inftyfeld.
    FIELD /SIE/HR_IDP_VF1T-FELDNAME.
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /SIE/HR_IDP_VF1T-FELDNAME.
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.

  MODULE EXIT_CODE_F4.          " XFT

 MODULE LISTE_AFTER_LOOP.
