FUNCTION-POOL /SIE/HR_IDP_KONF  MESSAGE-ID /SIE/HR_IDP_MESSAGES.

TYPES: BEGIN OF T_MATRIX
     , ROLE(2) TYPE C
     , PERNR TYPE XFLAG
     , UNAME TYPE XFLAG
     , ORGEH TYPE XFLAG
     , EMAIL TYPE XFLAG
     , END OF T_MATRIX
     , T_ITAB_MATRIX TYPE STANDARD TABLE OF T_MATRIX INITIAL SIZE 0
     .
