PROCESS BEFORE OUTPUT.
 MODULE INIT_OKCODES.
 MODULE INIT_2500.
 MODULE READ_2500.
 MODULE READ_S1LT.
 MODULE SET_STATUS.
*
PROCESS AFTER INPUT.
 MODULE EXIT_COMMAND_2500 AT EXIT-COMMAND.
 MODULE COPY_OK_CODE.
 CHAIN.
  FIELD /SIE/HR_IDP_S1-IFCID.
 ENDCHAIN.
 MODULE SYNC_2500.

* Prüfung ob die Schnittstelle existiert!
 FIELD /SIE/HR_IDP_S1-IFCID SELECT * FROM /SIE/HR_IDP_S1
                            WHERE IFCID = /SIE/HR_IDP_S1-IFCID
                            WHENEVER NOT FOUND SEND ERRORMESSAGE 304.
 MODULE ENQUEUE.
 MODULE USER_COMMAND_2500.
