*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /SIE/HR_IDP_VC1T................................*
FORM GET_DATA_/SIE/HR_IDP_VC1T.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /SIE/HR_IDP_C1 WHERE
(VIM_WHERETAB) .
    CLEAR /SIE/HR_IDP_VC1T .
/SIE/HR_IDP_VC1T-MANDT =
/SIE/HR_IDP_C1-MANDT .
/SIE/HR_IDP_VC1T-KONVNAM =
/SIE/HR_IDP_C1-KONVNAM .
/SIE/HR_IDP_VC1T-FUBANAM =
/SIE/HR_IDP_C1-FUBANAM .
/SIE/HR_IDP_VC1T-CR_UNAME =
/SIE/HR_IDP_C1-CR_UNAME .
/SIE/HR_IDP_VC1T-CR_DATUM =
/SIE/HR_IDP_C1-CR_DATUM .
/SIE/HR_IDP_VC1T-CR_UZEIT =
/SIE/HR_IDP_C1-CR_UZEIT .
/SIE/HR_IDP_VC1T-CR_REPID =
/SIE/HR_IDP_C1-CR_REPID .
/SIE/HR_IDP_VC1T-UNAME =
/SIE/HR_IDP_C1-UNAME .
/SIE/HR_IDP_VC1T-DATUM =
/SIE/HR_IDP_C1-DATUM .
/SIE/HR_IDP_VC1T-UZEIT =
/SIE/HR_IDP_C1-UZEIT .
/SIE/HR_IDP_VC1T-REPID =
/SIE/HR_IDP_C1-REPID .
/SIE/HR_IDP_VC1T-KONVFLAG =
/SIE/HR_IDP_C1-KONVFLAG .
/SIE/HR_IDP_VC1T-KONVLIST =
/SIE/HR_IDP_C1-KONVLIST .
/SIE/HR_IDP_VC1T-KONVPARA =
/SIE/HR_IDP_C1-KONVPARA .
/SIE/HR_IDP_VC1T-KONVLENG =
/SIE/HR_IDP_C1-KONVLENG .
    SELECT SINGLE * FROM /SIE/HR_IDP_C1T WHERE
KONVNAM = /SIE/HR_IDP_C1-KONVNAM AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
/SIE/HR_IDP_VC1T-IDENT =
/SIE/HR_IDP_C1T-IDENT .
    ENDIF.
<VIM_TOTAL_STRUC> = /SIE/HR_IDP_VC1T.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/SIE/HR_IDP_VC1T .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /SIE/HR_IDP_VC1T.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/SIE/HR_IDP_VC1T-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /SIE/HR_IDP_C1 WHERE
  KONVNAM = /SIE/HR_IDP_VC1T-KONVNAM .
    IF SY-SUBRC = 0.
    DELETE /SIE/HR_IDP_C1 .
    ENDIF.
    DELETE FROM /SIE/HR_IDP_C1T WHERE
    KONVNAM = /SIE/HR_IDP_C1-KONVNAM .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /SIE/HR_IDP_C1 WHERE
  KONVNAM = /SIE/HR_IDP_VC1T-KONVNAM .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /SIE/HR_IDP_C1.
    ENDIF.
/SIE/HR_IDP_C1-MANDT =
/SIE/HR_IDP_VC1T-MANDT .
/SIE/HR_IDP_C1-KONVNAM =
/SIE/HR_IDP_VC1T-KONVNAM .
/SIE/HR_IDP_C1-FUBANAM =
/SIE/HR_IDP_VC1T-FUBANAM .
/SIE/HR_IDP_C1-CR_UNAME =
/SIE/HR_IDP_VC1T-CR_UNAME .
/SIE/HR_IDP_C1-CR_DATUM =
/SIE/HR_IDP_VC1T-CR_DATUM .
/SIE/HR_IDP_C1-CR_UZEIT =
/SIE/HR_IDP_VC1T-CR_UZEIT .
/SIE/HR_IDP_C1-CR_REPID =
/SIE/HR_IDP_VC1T-CR_REPID .
/SIE/HR_IDP_C1-UNAME =
/SIE/HR_IDP_VC1T-UNAME .
/SIE/HR_IDP_C1-DATUM =
/SIE/HR_IDP_VC1T-DATUM .
/SIE/HR_IDP_C1-UZEIT =
/SIE/HR_IDP_VC1T-UZEIT .
/SIE/HR_IDP_C1-REPID =
/SIE/HR_IDP_VC1T-REPID .
/SIE/HR_IDP_C1-KONVFLAG =
/SIE/HR_IDP_VC1T-KONVFLAG .
/SIE/HR_IDP_C1-KONVLIST =
/SIE/HR_IDP_VC1T-KONVLIST .
/SIE/HR_IDP_C1-KONVPARA =
/SIE/HR_IDP_VC1T-KONVPARA .
/SIE/HR_IDP_C1-KONVLENG =
/SIE/HR_IDP_VC1T-KONVLENG .
    IF SY-SUBRC = 0.
    UPDATE /SIE/HR_IDP_C1 .
    ELSE.
    INSERT /SIE/HR_IDP_C1 .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM /SIE/HR_IDP_C1T WHERE
    KONVNAM = /SIE/HR_IDP_C1-KONVNAM AND
    SPRAS = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR /SIE/HR_IDP_C1T.
/SIE/HR_IDP_C1T-KONVNAM =
/SIE/HR_IDP_C1-KONVNAM .
/SIE/HR_IDP_C1T-SPRAS =
SY-LANGU .
      ENDIF.
/SIE/HR_IDP_C1T-IDENT =
/SIE/HR_IDP_VC1T-IDENT .
    IF SY-SUBRC = 0.
    UPDATE /SIE/HR_IDP_C1T .
    ELSE.
    INSERT /SIE/HR_IDP_C1T .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/SIE/HR_IDP_VC1T-UPD_FLAG,
STATUS_/SIE/HR_IDP_VC1T-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/SIE/HR_IDP_VC1T.
  SELECT SINGLE * FROM /SIE/HR_IDP_C1 WHERE
KONVNAM = /SIE/HR_IDP_VC1T-KONVNAM .
/SIE/HR_IDP_VC1T-MANDT =
/SIE/HR_IDP_C1-MANDT .
/SIE/HR_IDP_VC1T-KONVNAM =
/SIE/HR_IDP_C1-KONVNAM .
/SIE/HR_IDP_VC1T-FUBANAM =
/SIE/HR_IDP_C1-FUBANAM .
/SIE/HR_IDP_VC1T-CR_UNAME =
/SIE/HR_IDP_C1-CR_UNAME .
/SIE/HR_IDP_VC1T-CR_DATUM =
/SIE/HR_IDP_C1-CR_DATUM .
/SIE/HR_IDP_VC1T-CR_UZEIT =
/SIE/HR_IDP_C1-CR_UZEIT .
/SIE/HR_IDP_VC1T-CR_REPID =
/SIE/HR_IDP_C1-CR_REPID .
/SIE/HR_IDP_VC1T-UNAME =
/SIE/HR_IDP_C1-UNAME .
/SIE/HR_IDP_VC1T-DATUM =
/SIE/HR_IDP_C1-DATUM .
/SIE/HR_IDP_VC1T-UZEIT =
/SIE/HR_IDP_C1-UZEIT .
/SIE/HR_IDP_VC1T-REPID =
/SIE/HR_IDP_C1-REPID .
/SIE/HR_IDP_VC1T-KONVFLAG =
/SIE/HR_IDP_C1-KONVFLAG .
/SIE/HR_IDP_VC1T-KONVLIST =
/SIE/HR_IDP_C1-KONVLIST .
/SIE/HR_IDP_VC1T-KONVPARA =
/SIE/HR_IDP_C1-KONVPARA .
/SIE/HR_IDP_VC1T-KONVLENG =
/SIE/HR_IDP_C1-KONVLENG .
    SELECT SINGLE * FROM /SIE/HR_IDP_C1T WHERE
KONVNAM = /SIE/HR_IDP_C1-KONVNAM AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
/SIE/HR_IDP_VC1T-IDENT =
/SIE/HR_IDP_C1T-IDENT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /SIE/HR_IDP_VC1T-IDENT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/SIE/HR_IDP_VC1T USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /SIE/HR_IDP_VC1T-KONVNAM TO
/SIE/HR_IDP_C1-KONVNAM .
MOVE /SIE/HR_IDP_VC1T-MANDT TO
/SIE/HR_IDP_C1-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/SIE/HR_IDP_C1'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /SIE/HR_IDP_C1 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/SIE/HR_IDP_C1'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE /SIE/HR_IDP_C1-KONVNAM TO
/SIE/HR_IDP_C1T-KONVNAM .
MOVE SY-LANGU TO
/SIE/HR_IDP_C1T-SPRAS .
MOVE /SIE/HR_IDP_VC1T-MANDT TO
/SIE/HR_IDP_C1T-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/SIE/HR_IDP_C1T'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /SIE/HR_IDP_C1T TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/SIE/HR_IDP_C1T'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /SIE/HR_IDP_VF0T................................*
FORM GET_DATA_/SIE/HR_IDP_VF0T.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /SIE/HR_IDP_F0 WHERE
(VIM_WHERETAB) .
    CLEAR /SIE/HR_IDP_VF0T .
/SIE/HR_IDP_VF0T-MANDT =
/SIE/HR_IDP_F0-MANDT .
/SIE/HR_IDP_VF0T-GRTYP =
/SIE/HR_IDP_F0-GRTYP .
/SIE/HR_IDP_VF0T-GRKEY =
/SIE/HR_IDP_F0-GRKEY .
/SIE/HR_IDP_VF0T-SORTN =
/SIE/HR_IDP_F0-SORTN .
/SIE/HR_IDP_VF0T-PARENT =
/SIE/HR_IDP_F0-PARENT .
/SIE/HR_IDP_VF0T-CR_UNAME =
/SIE/HR_IDP_F0-CR_UNAME .
/SIE/HR_IDP_VF0T-CR_DATUM =
/SIE/HR_IDP_F0-CR_DATUM .
/SIE/HR_IDP_VF0T-CR_UZEIT =
/SIE/HR_IDP_F0-CR_UZEIT .
/SIE/HR_IDP_VF0T-CR_REPID =
/SIE/HR_IDP_F0-CR_REPID .
/SIE/HR_IDP_VF0T-UNAME =
/SIE/HR_IDP_F0-UNAME .
/SIE/HR_IDP_VF0T-DATUM =
/SIE/HR_IDP_F0-DATUM .
/SIE/HR_IDP_VF0T-UZEIT =
/SIE/HR_IDP_F0-UZEIT .
/SIE/HR_IDP_VF0T-REPID =
/SIE/HR_IDP_F0-REPID .
    SELECT SINGLE * FROM /SIE/HR_IDP_F0T WHERE
GRTYP = /SIE/HR_IDP_F0-GRTYP AND
GRKEY = /SIE/HR_IDP_F0-GRKEY AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
/SIE/HR_IDP_VF0T-IDENT =
/SIE/HR_IDP_F0T-IDENT .
    ENDIF.
<VIM_TOTAL_STRUC> = /SIE/HR_IDP_VF0T.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/SIE/HR_IDP_VF0T .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /SIE/HR_IDP_VF0T.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/SIE/HR_IDP_VF0T-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /SIE/HR_IDP_F0 WHERE
  GRTYP = /SIE/HR_IDP_VF0T-GRTYP AND
  GRKEY = /SIE/HR_IDP_VF0T-GRKEY .
    IF SY-SUBRC = 0.
    DELETE /SIE/HR_IDP_F0 .
    ENDIF.
    DELETE FROM /SIE/HR_IDP_F0T WHERE
    GRTYP = /SIE/HR_IDP_F0-GRTYP AND
    GRKEY = /SIE/HR_IDP_F0-GRKEY .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /SIE/HR_IDP_F0 WHERE
  GRTYP = /SIE/HR_IDP_VF0T-GRTYP AND
  GRKEY = /SIE/HR_IDP_VF0T-GRKEY .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /SIE/HR_IDP_F0.
    ENDIF.
/SIE/HR_IDP_F0-MANDT =
/SIE/HR_IDP_VF0T-MANDT .
/SIE/HR_IDP_F0-GRTYP =
/SIE/HR_IDP_VF0T-GRTYP .
/SIE/HR_IDP_F0-GRKEY =
/SIE/HR_IDP_VF0T-GRKEY .
/SIE/HR_IDP_F0-SORTN =
/SIE/HR_IDP_VF0T-SORTN .
/SIE/HR_IDP_F0-PARENT =
/SIE/HR_IDP_VF0T-PARENT .
/SIE/HR_IDP_F0-CR_UNAME =
/SIE/HR_IDP_VF0T-CR_UNAME .
/SIE/HR_IDP_F0-CR_DATUM =
/SIE/HR_IDP_VF0T-CR_DATUM .
/SIE/HR_IDP_F0-CR_UZEIT =
/SIE/HR_IDP_VF0T-CR_UZEIT .
/SIE/HR_IDP_F0-CR_REPID =
/SIE/HR_IDP_VF0T-CR_REPID .
/SIE/HR_IDP_F0-UNAME =
/SIE/HR_IDP_VF0T-UNAME .
/SIE/HR_IDP_F0-DATUM =
/SIE/HR_IDP_VF0T-DATUM .
/SIE/HR_IDP_F0-UZEIT =
/SIE/HR_IDP_VF0T-UZEIT .
/SIE/HR_IDP_F0-REPID =
/SIE/HR_IDP_VF0T-REPID .
    IF SY-SUBRC = 0.
    UPDATE /SIE/HR_IDP_F0 .
    ELSE.
    INSERT /SIE/HR_IDP_F0 .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM /SIE/HR_IDP_F0T WHERE
    GRTYP = /SIE/HR_IDP_F0-GRTYP AND
    GRKEY = /SIE/HR_IDP_F0-GRKEY AND
    SPRAS = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR /SIE/HR_IDP_F0T.
/SIE/HR_IDP_F0T-GRTYP =
/SIE/HR_IDP_F0-GRTYP .
/SIE/HR_IDP_F0T-GRKEY =
/SIE/HR_IDP_F0-GRKEY .
/SIE/HR_IDP_F0T-SPRAS =
SY-LANGU .
      ENDIF.
/SIE/HR_IDP_F0T-IDENT =
/SIE/HR_IDP_VF0T-IDENT .
    IF SY-SUBRC = 0.
    UPDATE /SIE/HR_IDP_F0T .
    ELSE.
    INSERT /SIE/HR_IDP_F0T .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/SIE/HR_IDP_VF0T-UPD_FLAG,
STATUS_/SIE/HR_IDP_VF0T-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/SIE/HR_IDP_VF0T.
  SELECT SINGLE * FROM /SIE/HR_IDP_F0 WHERE
GRTYP = /SIE/HR_IDP_VF0T-GRTYP AND
GRKEY = /SIE/HR_IDP_VF0T-GRKEY .
/SIE/HR_IDP_VF0T-MANDT =
/SIE/HR_IDP_F0-MANDT .
/SIE/HR_IDP_VF0T-GRTYP =
/SIE/HR_IDP_F0-GRTYP .
/SIE/HR_IDP_VF0T-GRKEY =
/SIE/HR_IDP_F0-GRKEY .
/SIE/HR_IDP_VF0T-SORTN =
/SIE/HR_IDP_F0-SORTN .
/SIE/HR_IDP_VF0T-PARENT =
/SIE/HR_IDP_F0-PARENT .
/SIE/HR_IDP_VF0T-CR_UNAME =
/SIE/HR_IDP_F0-CR_UNAME .
/SIE/HR_IDP_VF0T-CR_DATUM =
/SIE/HR_IDP_F0-CR_DATUM .
/SIE/HR_IDP_VF0T-CR_UZEIT =
/SIE/HR_IDP_F0-CR_UZEIT .
/SIE/HR_IDP_VF0T-CR_REPID =
/SIE/HR_IDP_F0-CR_REPID .
/SIE/HR_IDP_VF0T-UNAME =
/SIE/HR_IDP_F0-UNAME .
/SIE/HR_IDP_VF0T-DATUM =
/SIE/HR_IDP_F0-DATUM .
/SIE/HR_IDP_VF0T-UZEIT =
/SIE/HR_IDP_F0-UZEIT .
/SIE/HR_IDP_VF0T-REPID =
/SIE/HR_IDP_F0-REPID .
    SELECT SINGLE * FROM /SIE/HR_IDP_F0T WHERE
GRTYP = /SIE/HR_IDP_F0-GRTYP AND
GRKEY = /SIE/HR_IDP_F0-GRKEY AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
/SIE/HR_IDP_VF0T-IDENT =
/SIE/HR_IDP_F0T-IDENT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /SIE/HR_IDP_VF0T-IDENT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/SIE/HR_IDP_VF0T USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /SIE/HR_IDP_VF0T-GRTYP TO
/SIE/HR_IDP_F0-GRTYP .
MOVE /SIE/HR_IDP_VF0T-GRKEY TO
/SIE/HR_IDP_F0-GRKEY .
MOVE /SIE/HR_IDP_VF0T-MANDT TO
/SIE/HR_IDP_F0-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/SIE/HR_IDP_F0'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /SIE/HR_IDP_F0 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/SIE/HR_IDP_F0'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE /SIE/HR_IDP_F0-GRTYP TO
/SIE/HR_IDP_F0T-GRTYP .
MOVE /SIE/HR_IDP_F0-GRKEY TO
/SIE/HR_IDP_F0T-GRKEY .
MOVE SY-LANGU TO
/SIE/HR_IDP_F0T-SPRAS .
MOVE /SIE/HR_IDP_VF0T-MANDT TO
/SIE/HR_IDP_F0T-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/SIE/HR_IDP_F0T'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /SIE/HR_IDP_F0T TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/SIE/HR_IDP_F0T'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /SIE/HR_IDP_VF1S................................*
FORM GET_DATA_/SIE/HR_IDP_VF1S.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /SIE/HR_IDP_F1S WHERE
(VIM_WHERETAB) .
    CLEAR /SIE/HR_IDP_VF1S .
/SIE/HR_IDP_VF1S-MANDT =
/SIE/HR_IDP_F1S-MANDT .
/SIE/HR_IDP_VF1S-FELDNAME =
/SIE/HR_IDP_F1S-FELDNAME .
/SIE/HR_IDP_VF1S-SLNAM =
/SIE/HR_IDP_F1S-SLNAM .
/SIE/HR_IDP_VF1S-KZVSR =
/SIE/HR_IDP_F1S-KZVSR .
/SIE/HR_IDP_VF1S-CR_UNAME =
/SIE/HR_IDP_F1S-CR_UNAME .
/SIE/HR_IDP_VF1S-CR_DATUM =
/SIE/HR_IDP_F1S-CR_DATUM .
/SIE/HR_IDP_VF1S-CR_UZEIT =
/SIE/HR_IDP_F1S-CR_UZEIT .
/SIE/HR_IDP_VF1S-CR_REPID =
/SIE/HR_IDP_F1S-CR_REPID .
/SIE/HR_IDP_VF1S-UNAME =
/SIE/HR_IDP_F1S-UNAME .
/SIE/HR_IDP_VF1S-DATUM =
/SIE/HR_IDP_F1S-DATUM .
/SIE/HR_IDP_VF1S-UZEIT =
/SIE/HR_IDP_F1S-UZEIT .
/SIE/HR_IDP_VF1S-REPID =
/SIE/HR_IDP_F1S-REPID .
/SIE/HR_IDP_VF1S-GRKEY =
/SIE/HR_IDP_F1S-GRKEY .
/SIE/HR_IDP_VF1S-SORTN =
/SIE/HR_IDP_F1S-SORTN .
    SELECT SINGLE * FROM /SIE/HR_IDP_F1 WHERE
FELDNAME = /SIE/HR_IDP_F1S-FELDNAME .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /SIE/HR_IDP_F1T WHERE
FELDNAME = /SIE/HR_IDP_F1-FELDNAME AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/SIE/HR_IDP_VF1S-IDENT =
/SIE/HR_IDP_F1T-IDENT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = /SIE/HR_IDP_VF1S.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/SIE/HR_IDP_VF1S .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /SIE/HR_IDP_VF1S.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/SIE/HR_IDP_VF1S-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /SIE/HR_IDP_F1S WHERE
  FELDNAME = /SIE/HR_IDP_VF1S-FELDNAME .
    IF SY-SUBRC = 0.
    DELETE /SIE/HR_IDP_F1S .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /SIE/HR_IDP_F1S WHERE
  FELDNAME = /SIE/HR_IDP_VF1S-FELDNAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /SIE/HR_IDP_F1S.
    ENDIF.
/SIE/HR_IDP_F1S-MANDT =
/SIE/HR_IDP_VF1S-MANDT .
/SIE/HR_IDP_F1S-FELDNAME =
/SIE/HR_IDP_VF1S-FELDNAME .
/SIE/HR_IDP_F1S-SLNAM =
/SIE/HR_IDP_VF1S-SLNAM .
/SIE/HR_IDP_F1S-KZVSR =
/SIE/HR_IDP_VF1S-KZVSR .
/SIE/HR_IDP_F1S-CR_UNAME =
/SIE/HR_IDP_VF1S-CR_UNAME .
/SIE/HR_IDP_F1S-CR_DATUM =
/SIE/HR_IDP_VF1S-CR_DATUM .
/SIE/HR_IDP_F1S-CR_UZEIT =
/SIE/HR_IDP_VF1S-CR_UZEIT .
/SIE/HR_IDP_F1S-CR_REPID =
/SIE/HR_IDP_VF1S-CR_REPID .
/SIE/HR_IDP_F1S-UNAME =
/SIE/HR_IDP_VF1S-UNAME .
/SIE/HR_IDP_F1S-DATUM =
/SIE/HR_IDP_VF1S-DATUM .
/SIE/HR_IDP_F1S-UZEIT =
/SIE/HR_IDP_VF1S-UZEIT .
/SIE/HR_IDP_F1S-REPID =
/SIE/HR_IDP_VF1S-REPID .
/SIE/HR_IDP_F1S-GRKEY =
/SIE/HR_IDP_VF1S-GRKEY .
/SIE/HR_IDP_F1S-SORTN =
/SIE/HR_IDP_VF1S-SORTN .
    IF SY-SUBRC = 0.
    UPDATE /SIE/HR_IDP_F1S .
    ELSE.
    INSERT /SIE/HR_IDP_F1S .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/SIE/HR_IDP_VF1S-UPD_FLAG,
STATUS_/SIE/HR_IDP_VF1S-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/SIE/HR_IDP_VF1S.
  SELECT SINGLE * FROM /SIE/HR_IDP_F1S WHERE
FELDNAME = /SIE/HR_IDP_VF1S-FELDNAME .
/SIE/HR_IDP_VF1S-MANDT =
/SIE/HR_IDP_F1S-MANDT .
/SIE/HR_IDP_VF1S-FELDNAME =
/SIE/HR_IDP_F1S-FELDNAME .
/SIE/HR_IDP_VF1S-SLNAM =
/SIE/HR_IDP_F1S-SLNAM .
/SIE/HR_IDP_VF1S-KZVSR =
/SIE/HR_IDP_F1S-KZVSR .
/SIE/HR_IDP_VF1S-CR_UNAME =
/SIE/HR_IDP_F1S-CR_UNAME .
/SIE/HR_IDP_VF1S-CR_DATUM =
/SIE/HR_IDP_F1S-CR_DATUM .
/SIE/HR_IDP_VF1S-CR_UZEIT =
/SIE/HR_IDP_F1S-CR_UZEIT .
/SIE/HR_IDP_VF1S-CR_REPID =
/SIE/HR_IDP_F1S-CR_REPID .
/SIE/HR_IDP_VF1S-UNAME =
/SIE/HR_IDP_F1S-UNAME .
/SIE/HR_IDP_VF1S-DATUM =
/SIE/HR_IDP_F1S-DATUM .
/SIE/HR_IDP_VF1S-UZEIT =
/SIE/HR_IDP_F1S-UZEIT .
/SIE/HR_IDP_VF1S-REPID =
/SIE/HR_IDP_F1S-REPID .
/SIE/HR_IDP_VF1S-GRKEY =
/SIE/HR_IDP_F1S-GRKEY .
/SIE/HR_IDP_VF1S-SORTN =
/SIE/HR_IDP_F1S-SORTN .
    SELECT SINGLE * FROM /SIE/HR_IDP_F1 WHERE
FELDNAME = /SIE/HR_IDP_F1S-FELDNAME .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /SIE/HR_IDP_F1T WHERE
FELDNAME = /SIE/HR_IDP_F1-FELDNAME AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/SIE/HR_IDP_VF1S-IDENT =
/SIE/HR_IDP_F1T-IDENT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /SIE/HR_IDP_VF1S-IDENT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /SIE/HR_IDP_VF1S-IDENT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/SIE/HR_IDP_VF1S USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /SIE/HR_IDP_VF1S-FELDNAME TO
/SIE/HR_IDP_F1S-FELDNAME .
MOVE /SIE/HR_IDP_VF1S-MANDT TO
/SIE/HR_IDP_F1S-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/SIE/HR_IDP_F1S'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /SIE/HR_IDP_F1S TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/SIE/HR_IDP_F1S'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/SIE/HR_IDP_VF1S USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/SIE/HR_IDP_F1S-MANDT =
/SIE/HR_IDP_VF1S-MANDT .
/SIE/HR_IDP_F1S-FELDNAME =
/SIE/HR_IDP_VF1S-FELDNAME .
/SIE/HR_IDP_F1S-SLNAM =
/SIE/HR_IDP_VF1S-SLNAM .
/SIE/HR_IDP_F1S-KZVSR =
/SIE/HR_IDP_VF1S-KZVSR .
/SIE/HR_IDP_F1S-CR_UNAME =
/SIE/HR_IDP_VF1S-CR_UNAME .
/SIE/HR_IDP_F1S-CR_DATUM =
/SIE/HR_IDP_VF1S-CR_DATUM .
/SIE/HR_IDP_F1S-CR_UZEIT =
/SIE/HR_IDP_VF1S-CR_UZEIT .
/SIE/HR_IDP_F1S-CR_REPID =
/SIE/HR_IDP_VF1S-CR_REPID .
/SIE/HR_IDP_F1S-UNAME =
/SIE/HR_IDP_VF1S-UNAME .
/SIE/HR_IDP_F1S-DATUM =
/SIE/HR_IDP_VF1S-DATUM .
/SIE/HR_IDP_F1S-UZEIT =
/SIE/HR_IDP_VF1S-UZEIT .
/SIE/HR_IDP_F1S-REPID =
/SIE/HR_IDP_VF1S-REPID .
/SIE/HR_IDP_F1S-GRKEY =
/SIE/HR_IDP_VF1S-GRKEY .
/SIE/HR_IDP_F1S-SORTN =
/SIE/HR_IDP_VF1S-SORTN .
    SELECT SINGLE * FROM /SIE/HR_IDP_F1 WHERE
FELDNAME = /SIE/HR_IDP_F1S-FELDNAME .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /SIE/HR_IDP_F1T WHERE
FELDNAME = /SIE/HR_IDP_F1-FELDNAME AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/SIE/HR_IDP_VF1S-IDENT =
/SIE/HR_IDP_F1T-IDENT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /SIE/HR_IDP_VF1S-IDENT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /SIE/HR_IDP_VF1S-IDENT .
    ENDIF.
ENDFORM.
*...processing: /SIE/HR_IDP_VF1T................................*
FORM GET_DATA_/SIE/HR_IDP_VF1T.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /SIE/HR_IDP_F1 WHERE
(VIM_WHERETAB) .
    CLEAR /SIE/HR_IDP_VF1T .
/SIE/HR_IDP_VF1T-MANDT =
/SIE/HR_IDP_F1-MANDT .
/SIE/HR_IDP_VF1T-FELDNAME =
/SIE/HR_IDP_F1-FELDNAME .
/SIE/HR_IDP_VF1T-GRKEY =
/SIE/HR_IDP_F1-GRKEY .
/SIE/HR_IDP_VF1T-SORTN =
/SIE/HR_IDP_F1-SORTN .
/SIE/HR_IDP_VF1T-DPFTYPE =
/SIE/HR_IDP_F1-DPFTYPE .
/SIE/HR_IDP_VF1T-INFTY =
/SIE/HR_IDP_F1-INFTY .
/SIE/HR_IDP_VF1T-SUBTY =
/SIE/HR_IDP_F1-SUBTY .
/SIE/HR_IDP_VF1T-INFTYFELD =
/SIE/HR_IDP_F1-INFTYFELD .
/SIE/HR_IDP_VF1T-KONVSTRG =
/SIE/HR_IDP_F1-KONVSTRG .
/SIE/HR_IDP_VF1T-KONVNAME =
/SIE/HR_IDP_F1-KONVNAME .
/SIE/HR_IDP_VF1T-BEGRIFF =
/SIE/HR_IDP_F1-BEGRIFF .
/SIE/HR_IDP_VF1T-ACLTAB =
/SIE/HR_IDP_F1-ACLTAB .
/SIE/HR_IDP_VF1T-ACLFELD =
/SIE/HR_IDP_F1-ACLFELD .
/SIE/HR_IDP_VF1T-RTLGART =
/SIE/HR_IDP_F1-RTLGART .
/SIE/HR_IDP_VF1T-RTKZ =
/SIE/HR_IDP_F1-RTKZ .
/SIE/HR_IDP_VF1T-CR_UNAME =
/SIE/HR_IDP_F1-CR_UNAME .
/SIE/HR_IDP_VF1T-CR_DATUM =
/SIE/HR_IDP_F1-CR_DATUM .
/SIE/HR_IDP_VF1T-CR_UZEIT =
/SIE/HR_IDP_F1-CR_UZEIT .
/SIE/HR_IDP_VF1T-CR_REPID =
/SIE/HR_IDP_F1-CR_REPID .
/SIE/HR_IDP_VF1T-UNAME =
/SIE/HR_IDP_F1-UNAME .
/SIE/HR_IDP_VF1T-DATUM =
/SIE/HR_IDP_F1-DATUM .
/SIE/HR_IDP_VF1T-UZEIT =
/SIE/HR_IDP_F1-UZEIT .
/SIE/HR_IDP_VF1T-REPID =
/SIE/HR_IDP_F1-REPID .
/SIE/HR_IDP_VF1T-AGGREGATE =
/SIE/HR_IDP_F1-AGGREGATE .
/SIE/HR_IDP_VF1T-SINGULAR =
/SIE/HR_IDP_F1-SINGULAR .
/SIE/HR_IDP_VF1T-KZHDFT =
/SIE/HR_IDP_F1-KZHDFT .
/SIE/HR_IDP_VF1T-FL_MODIF =
/SIE/HR_IDP_F1-FL_MODIF .
/SIE/HR_IDP_VF1T-STRU_VAL =
/SIE/HR_IDP_F1-STRU_VAL .
    SELECT SINGLE * FROM /SIE/HR_IDP_F1T WHERE
FELDNAME = /SIE/HR_IDP_F1-FELDNAME AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
/SIE/HR_IDP_VF1T-IDENT =
/SIE/HR_IDP_F1T-IDENT .
    ENDIF.
<VIM_TOTAL_STRUC> = /SIE/HR_IDP_VF1T.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/SIE/HR_IDP_VF1T .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /SIE/HR_IDP_VF1T.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/SIE/HR_IDP_VF1T-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /SIE/HR_IDP_F1 WHERE
  FELDNAME = /SIE/HR_IDP_VF1T-FELDNAME .
    IF SY-SUBRC = 0.
    DELETE /SIE/HR_IDP_F1 .
    ENDIF.
    DELETE FROM /SIE/HR_IDP_F1T WHERE
    FELDNAME = /SIE/HR_IDP_F1-FELDNAME .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /SIE/HR_IDP_F1 WHERE
  FELDNAME = /SIE/HR_IDP_VF1T-FELDNAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /SIE/HR_IDP_F1.
    ENDIF.
/SIE/HR_IDP_F1-MANDT =
/SIE/HR_IDP_VF1T-MANDT .
/SIE/HR_IDP_F1-FELDNAME =
/SIE/HR_IDP_VF1T-FELDNAME .
/SIE/HR_IDP_F1-GRKEY =
/SIE/HR_IDP_VF1T-GRKEY .
/SIE/HR_IDP_F1-SORTN =
/SIE/HR_IDP_VF1T-SORTN .
/SIE/HR_IDP_F1-DPFTYPE =
/SIE/HR_IDP_VF1T-DPFTYPE .
/SIE/HR_IDP_F1-INFTY =
/SIE/HR_IDP_VF1T-INFTY .
/SIE/HR_IDP_F1-SUBTY =
/SIE/HR_IDP_VF1T-SUBTY .
/SIE/HR_IDP_F1-INFTYFELD =
/SIE/HR_IDP_VF1T-INFTYFELD .
/SIE/HR_IDP_F1-KONVSTRG =
/SIE/HR_IDP_VF1T-KONVSTRG .
/SIE/HR_IDP_F1-KONVNAME =
/SIE/HR_IDP_VF1T-KONVNAME .
/SIE/HR_IDP_F1-BEGRIFF =
/SIE/HR_IDP_VF1T-BEGRIFF .
/SIE/HR_IDP_F1-ACLTAB =
/SIE/HR_IDP_VF1T-ACLTAB .
/SIE/HR_IDP_F1-ACLFELD =
/SIE/HR_IDP_VF1T-ACLFELD .
/SIE/HR_IDP_F1-RTLGART =
/SIE/HR_IDP_VF1T-RTLGART .
/SIE/HR_IDP_F1-RTKZ =
/SIE/HR_IDP_VF1T-RTKZ .
/SIE/HR_IDP_F1-CR_UNAME =
/SIE/HR_IDP_VF1T-CR_UNAME .
/SIE/HR_IDP_F1-CR_DATUM =
/SIE/HR_IDP_VF1T-CR_DATUM .
/SIE/HR_IDP_F1-CR_UZEIT =
/SIE/HR_IDP_VF1T-CR_UZEIT .
/SIE/HR_IDP_F1-CR_REPID =
/SIE/HR_IDP_VF1T-CR_REPID .
/SIE/HR_IDP_F1-UNAME =
/SIE/HR_IDP_VF1T-UNAME .
/SIE/HR_IDP_F1-DATUM =
/SIE/HR_IDP_VF1T-DATUM .
/SIE/HR_IDP_F1-UZEIT =
/SIE/HR_IDP_VF1T-UZEIT .
/SIE/HR_IDP_F1-REPID =
/SIE/HR_IDP_VF1T-REPID .
/SIE/HR_IDP_F1-AGGREGATE =
/SIE/HR_IDP_VF1T-AGGREGATE .
/SIE/HR_IDP_F1-SINGULAR =
/SIE/HR_IDP_VF1T-SINGULAR .
/SIE/HR_IDP_F1-KZHDFT =
/SIE/HR_IDP_VF1T-KZHDFT .
/SIE/HR_IDP_F1-FL_MODIF =
/SIE/HR_IDP_VF1T-FL_MODIF .
/SIE/HR_IDP_F1-STRU_VAL =
/SIE/HR_IDP_VF1T-STRU_VAL .
    IF SY-SUBRC = 0.
    UPDATE /SIE/HR_IDP_F1 .
    ELSE.
    INSERT /SIE/HR_IDP_F1 .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM /SIE/HR_IDP_F1T WHERE
    FELDNAME = /SIE/HR_IDP_F1-FELDNAME AND
    SPRAS = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR /SIE/HR_IDP_F1T.
/SIE/HR_IDP_F1T-FELDNAME =
/SIE/HR_IDP_F1-FELDNAME .
/SIE/HR_IDP_F1T-SPRAS =
SY-LANGU .
      ENDIF.
/SIE/HR_IDP_F1T-IDENT =
/SIE/HR_IDP_VF1T-IDENT .
    IF SY-SUBRC = 0.
    UPDATE /SIE/HR_IDP_F1T .
    ELSE.
    INSERT /SIE/HR_IDP_F1T .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/SIE/HR_IDP_VF1T-UPD_FLAG,
STATUS_/SIE/HR_IDP_VF1T-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/SIE/HR_IDP_VF1T.
  SELECT SINGLE * FROM /SIE/HR_IDP_F1 WHERE
FELDNAME = /SIE/HR_IDP_VF1T-FELDNAME .
/SIE/HR_IDP_VF1T-MANDT =
/SIE/HR_IDP_F1-MANDT .
/SIE/HR_IDP_VF1T-FELDNAME =
/SIE/HR_IDP_F1-FELDNAME .
/SIE/HR_IDP_VF1T-GRKEY =
/SIE/HR_IDP_F1-GRKEY .
/SIE/HR_IDP_VF1T-SORTN =
/SIE/HR_IDP_F1-SORTN .
/SIE/HR_IDP_VF1T-DPFTYPE =
/SIE/HR_IDP_F1-DPFTYPE .
/SIE/HR_IDP_VF1T-INFTY =
/SIE/HR_IDP_F1-INFTY .
/SIE/HR_IDP_VF1T-SUBTY =
/SIE/HR_IDP_F1-SUBTY .
/SIE/HR_IDP_VF1T-INFTYFELD =
/SIE/HR_IDP_F1-INFTYFELD .
/SIE/HR_IDP_VF1T-KONVSTRG =
/SIE/HR_IDP_F1-KONVSTRG .
/SIE/HR_IDP_VF1T-KONVNAME =
/SIE/HR_IDP_F1-KONVNAME .
/SIE/HR_IDP_VF1T-BEGRIFF =
/SIE/HR_IDP_F1-BEGRIFF .
/SIE/HR_IDP_VF1T-ACLTAB =
/SIE/HR_IDP_F1-ACLTAB .
/SIE/HR_IDP_VF1T-ACLFELD =
/SIE/HR_IDP_F1-ACLFELD .
/SIE/HR_IDP_VF1T-RTLGART =
/SIE/HR_IDP_F1-RTLGART .
/SIE/HR_IDP_VF1T-RTKZ =
/SIE/HR_IDP_F1-RTKZ .
/SIE/HR_IDP_VF1T-CR_UNAME =
/SIE/HR_IDP_F1-CR_UNAME .
/SIE/HR_IDP_VF1T-CR_DATUM =
/SIE/HR_IDP_F1-CR_DATUM .
/SIE/HR_IDP_VF1T-CR_UZEIT =
/SIE/HR_IDP_F1-CR_UZEIT .
/SIE/HR_IDP_VF1T-CR_REPID =
/SIE/HR_IDP_F1-CR_REPID .
/SIE/HR_IDP_VF1T-UNAME =
/SIE/HR_IDP_F1-UNAME .
/SIE/HR_IDP_VF1T-DATUM =
/SIE/HR_IDP_F1-DATUM .
/SIE/HR_IDP_VF1T-UZEIT =
/SIE/HR_IDP_F1-UZEIT .
/SIE/HR_IDP_VF1T-REPID =
/SIE/HR_IDP_F1-REPID .
/SIE/HR_IDP_VF1T-AGGREGATE =
/SIE/HR_IDP_F1-AGGREGATE .
/SIE/HR_IDP_VF1T-SINGULAR =
/SIE/HR_IDP_F1-SINGULAR .
/SIE/HR_IDP_VF1T-KZHDFT =
/SIE/HR_IDP_F1-KZHDFT .
/SIE/HR_IDP_VF1T-FL_MODIF =
/SIE/HR_IDP_F1-FL_MODIF .
/SIE/HR_IDP_VF1T-STRU_VAL =
/SIE/HR_IDP_F1-STRU_VAL .
    SELECT SINGLE * FROM /SIE/HR_IDP_F1T WHERE
FELDNAME = /SIE/HR_IDP_F1-FELDNAME AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
/SIE/HR_IDP_VF1T-IDENT =
/SIE/HR_IDP_F1T-IDENT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /SIE/HR_IDP_VF1T-IDENT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/SIE/HR_IDP_VF1T USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /SIE/HR_IDP_VF1T-FELDNAME TO
/SIE/HR_IDP_F1-FELDNAME .
MOVE /SIE/HR_IDP_VF1T-MANDT TO
/SIE/HR_IDP_F1-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/SIE/HR_IDP_F1'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /SIE/HR_IDP_F1 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/SIE/HR_IDP_F1'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE /SIE/HR_IDP_F1-FELDNAME TO
/SIE/HR_IDP_F1T-FELDNAME .
MOVE SY-LANGU TO
/SIE/HR_IDP_F1T-SPRAS .
MOVE /SIE/HR_IDP_VF1T-MANDT TO
/SIE/HR_IDP_F1T-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/SIE/HR_IDP_F1T'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /SIE/HR_IDP_F1T TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/SIE/HR_IDP_F1T'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: /SIE/HR_IDP_VS0T................................*
FORM GET_DATA_/SIE/HR_IDP_VS0T.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /SIE/HR_IDP_S0 WHERE
(VIM_WHERETAB) .
    CLEAR /SIE/HR_IDP_VS0T .
/SIE/HR_IDP_VS0T-MANDT =
/SIE/HR_IDP_S0-MANDT .
/SIE/HR_IDP_VS0T-AUTH_CLASS =
/SIE/HR_IDP_S0-AUTH_CLASS .
/SIE/HR_IDP_VS0T-UNAME =
/SIE/HR_IDP_S0-UNAME .
/SIE/HR_IDP_VS0T-DATUM =
/SIE/HR_IDP_S0-DATUM .
/SIE/HR_IDP_VS0T-UZEIT =
/SIE/HR_IDP_S0-UZEIT .
/SIE/HR_IDP_VS0T-REPID =
/SIE/HR_IDP_S0-REPID .
/SIE/HR_IDP_VS0T-CR_UNAME =
/SIE/HR_IDP_S0-CR_UNAME .
/SIE/HR_IDP_VS0T-CR_DATUM =
/SIE/HR_IDP_S0-CR_DATUM .
/SIE/HR_IDP_VS0T-CR_UZEIT =
/SIE/HR_IDP_S0-CR_UZEIT .
/SIE/HR_IDP_VS0T-CR_REPID =
/SIE/HR_IDP_S0-CR_REPID .
    SELECT SINGLE * FROM /SIE/HR_IDP_S0T WHERE
AUTH_CLASS = /SIE/HR_IDP_S0-AUTH_CLASS AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
/SIE/HR_IDP_VS0T-IDENT =
/SIE/HR_IDP_S0T-IDENT .
    ENDIF.
<VIM_TOTAL_STRUC> = /SIE/HR_IDP_VS0T.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/SIE/HR_IDP_VS0T .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /SIE/HR_IDP_VS0T.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/SIE/HR_IDP_VS0T-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /SIE/HR_IDP_S0 WHERE
  AUTH_CLASS = /SIE/HR_IDP_VS0T-AUTH_CLASS .
    IF SY-SUBRC = 0.
    DELETE /SIE/HR_IDP_S0 .
    ENDIF.
    DELETE FROM /SIE/HR_IDP_S0T WHERE
    AUTH_CLASS = /SIE/HR_IDP_S0-AUTH_CLASS .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /SIE/HR_IDP_S0 WHERE
  AUTH_CLASS = /SIE/HR_IDP_VS0T-AUTH_CLASS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /SIE/HR_IDP_S0.
    ENDIF.
/SIE/HR_IDP_S0-MANDT =
/SIE/HR_IDP_VS0T-MANDT .
/SIE/HR_IDP_S0-AUTH_CLASS =
/SIE/HR_IDP_VS0T-AUTH_CLASS .
/SIE/HR_IDP_S0-UNAME =
/SIE/HR_IDP_VS0T-UNAME .
/SIE/HR_IDP_S0-DATUM =
/SIE/HR_IDP_VS0T-DATUM .
/SIE/HR_IDP_S0-UZEIT =
/SIE/HR_IDP_VS0T-UZEIT .
/SIE/HR_IDP_S0-REPID =
/SIE/HR_IDP_VS0T-REPID .
/SIE/HR_IDP_S0-CR_UNAME =
/SIE/HR_IDP_VS0T-CR_UNAME .
/SIE/HR_IDP_S0-CR_DATUM =
/SIE/HR_IDP_VS0T-CR_DATUM .
/SIE/HR_IDP_S0-CR_UZEIT =
/SIE/HR_IDP_VS0T-CR_UZEIT .
/SIE/HR_IDP_S0-CR_REPID =
/SIE/HR_IDP_VS0T-CR_REPID .
    IF SY-SUBRC = 0.
    UPDATE /SIE/HR_IDP_S0 .
    ELSE.
    INSERT /SIE/HR_IDP_S0 .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM /SIE/HR_IDP_S0T WHERE
    AUTH_CLASS = /SIE/HR_IDP_S0-AUTH_CLASS AND
    SPRAS = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR /SIE/HR_IDP_S0T.
/SIE/HR_IDP_S0T-AUTH_CLASS =
/SIE/HR_IDP_S0-AUTH_CLASS .
/SIE/HR_IDP_S0T-SPRAS =
SY-LANGU .
      ENDIF.
/SIE/HR_IDP_S0T-IDENT =
/SIE/HR_IDP_VS0T-IDENT .
    IF SY-SUBRC = 0.
    UPDATE /SIE/HR_IDP_S0T .
    ELSE.
    INSERT /SIE/HR_IDP_S0T .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/SIE/HR_IDP_VS0T-UPD_FLAG,
STATUS_/SIE/HR_IDP_VS0T-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/SIE/HR_IDP_VS0T.
  SELECT SINGLE * FROM /SIE/HR_IDP_S0 WHERE
AUTH_CLASS = /SIE/HR_IDP_VS0T-AUTH_CLASS .
/SIE/HR_IDP_VS0T-MANDT =
/SIE/HR_IDP_S0-MANDT .
/SIE/HR_IDP_VS0T-AUTH_CLASS =
/SIE/HR_IDP_S0-AUTH_CLASS .
/SIE/HR_IDP_VS0T-UNAME =
/SIE/HR_IDP_S0-UNAME .
/SIE/HR_IDP_VS0T-DATUM =
/SIE/HR_IDP_S0-DATUM .
/SIE/HR_IDP_VS0T-UZEIT =
/SIE/HR_IDP_S0-UZEIT .
/SIE/HR_IDP_VS0T-REPID =
/SIE/HR_IDP_S0-REPID .
/SIE/HR_IDP_VS0T-CR_UNAME =
/SIE/HR_IDP_S0-CR_UNAME .
/SIE/HR_IDP_VS0T-CR_DATUM =
/SIE/HR_IDP_S0-CR_DATUM .
/SIE/HR_IDP_VS0T-CR_UZEIT =
/SIE/HR_IDP_S0-CR_UZEIT .
/SIE/HR_IDP_VS0T-CR_REPID =
/SIE/HR_IDP_S0-CR_REPID .
    SELECT SINGLE * FROM /SIE/HR_IDP_S0T WHERE
AUTH_CLASS = /SIE/HR_IDP_S0-AUTH_CLASS AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
/SIE/HR_IDP_VS0T-IDENT =
/SIE/HR_IDP_S0T-IDENT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /SIE/HR_IDP_VS0T-IDENT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/SIE/HR_IDP_VS0T USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /SIE/HR_IDP_VS0T-AUTH_CLASS TO
/SIE/HR_IDP_S0-AUTH_CLASS .
MOVE /SIE/HR_IDP_VS0T-MANDT TO
/SIE/HR_IDP_S0-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/SIE/HR_IDP_S0'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /SIE/HR_IDP_S0 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/SIE/HR_IDP_S0'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE /SIE/HR_IDP_S0-AUTH_CLASS TO
/SIE/HR_IDP_S0T-AUTH_CLASS .
MOVE SY-LANGU TO
/SIE/HR_IDP_S0T-SPRAS .
MOVE /SIE/HR_IDP_VS0T-MANDT TO
/SIE/HR_IDP_S0T-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/SIE/HR_IDP_S0T'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /SIE/HR_IDP_S0T TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/SIE/HR_IDP_S0T'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
