PROCESS BEFORE OUTPUT.
 MODULE SET_TRAN_STATUS_1000.
 MODULE INIT.
 MODULE CHECK_NEW.
 MODULE SET_STATUS.
 CALL SUBSCREEN SUBSCR_TITLE INCLUDING '/SIE/HR_IDP_IFC' C_TITL_SDYN.
 MODULE SET_DEQUEUE.
 MODULE READ_S1LT.
 CALL SUBSCREEN SUBSCR_VERSION INCLUDING '/SIE/HR_IDP_IFC' C_TCTL_SDYN.
 MODULE READ_S1F.
 MODULE MODIFY_SCREEN.
  MODULE SET_STATUS.
*
PROCESS AFTER INPUT.
 MODULE EXIT_COMMAND AT EXIT-COMMAND.
 MODULE COPY_OK_CODE.
* module check_change.
 CALL SUBSCREEN SUBSCR_TITLE.
 CALL SUBSCREEN SUBSCR_VERSION.
 MODULE SET_LINE_COUNT_1000.
 MODULE ENQUEUE.
 MODULE USER_COMMAND.












