*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 04.07.2001 at 13:03:32 by user MCH0341
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /SIE/LHR_IDP_SE54TOP.              " Global Data
  INCLUDE /SIE/LHR_IDP_SE54UXX.              " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /SIE/LHR_IDP_SE54F00                    . " subprograms
  INCLUDE /SIE/LHR_IDP_SE54I00                    . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
  INCLUDE /SIE/LHR_IDP_SE54O01.

  INCLUDE /SIE/LHR_IDP_SE54F01.              " Subprograms
  INCLUDE /SIE/LHR_IDP_SE54F02.
