PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
 TCTRL_/SIE/HR_IDP_V1                 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
   MODULE LISTE_DEACTIVATE.                         "MCH-20020208-160346
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /SIE/HR_IDP_V1-CURRENCY.
    FIELD /SIE/HR_IDP_V1-AMOUNT.
    FIELD /SIE/HR_IDP_V1-BEGDA.
    FIELD /SIE/HR_IDP_V1-ENDDA.
    FIELD /SIE/HR_IDP_V1-KOSTKATE.
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   CHAIN.                                           "MCH-20020208-160346
    FIELD /SIE/HR_IDP_V1-BEGDA.                     "MCH-20020208-160346
    FIELD /SIE/HR_IDP_V1-ENDDA.                     "MCH-20020208-160346
    MODULE TEMP_DELIMITATION ON CHAIN-REQUEST.      "MCH-20020208-160346
   ENDCHAIN.                                        "MCH-20020208-160346
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /SIE/HR_IDP_V1-ENDDA.
    FIELD /SIE/HR_IDP_V1-KOSTKATE.
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
