*----------------------------------------------------------------------*
*   INCLUDE /SIE/HR_IDP_TYPES                                          *
*----------------------------------------------------------------------*
*Änderungen: SIE001 Hierl 17.06.2004 Neue Tabelle S1PS für Filter auf
*                                    Feldebene eingebaut

TYPE-POOLS: VRM
          , SHLP
          .

INCLUDE /SIE/HR_IDP_BOOL.

TYPES: TY_TRCODE TYPE SYTCODE.
CONSTANTS: C_DISP_TCOD TYPE TY_TRCODE VALUE '/SIE/HR_IDP_IFC_DISP'
         , C_MODI_TCOD TYPE TY_TRCODE VALUE '/SIE/HR_IDP_IFC_MOD'
         , C_NEW__TCOD TYPE TY_TRCODE VALUE '/SIE/HR_IDP_IFC_NEW'
         , C_RELE_TCOD TYPE TY_TRCODE VALUE '/SIE/HR_IDP_IFC_RELE'
         , C_ACCP_TCOD TYPE TY_TRCODE VALUE '/SIE/HR_IDP_IFC_CONF'
         , C_RMOD_TCOD TYPE TY_TRCODE VALUE '/SIE/HR_IDP_IFC_RMOD'
         , C_ADHOC_TCOD TYPE TY_TRCODE VALUE '/SIE/HR_IDP_ADHOC'
         .

TYPES: TY_PFSTAT TYPE SYPFKEY.
CONSTANTS:
           C_DISP_PFST TYPE TY_PFSTAT VALUE 'IFC_GENERAL'
         , C_MODI_PFST TYPE TY_PFSTAT VALUE 'IFC_GENERAL'
         , C_COPY_PFST TYPE TY_PFSTAT VALUE 'IFC_COPY'
         .

TYPES: TY_PFMENU(20) TYPE C.
CONSTANTS: C_MODI_MUST TYPE TY_PFMENU VALUE 'IFC_MENU'
         , C_COPY_MUST TYPE TY_PFMENU VALUE 'IFC_COPY'
         , C_HEAD_MUST TYPE TY_PFMENU VALUE 'IFC_MENU_HEAD'
         , C_VARI_MUST TYPE TY_PFMENU VALUE 'IFC_MENU_VARI'
         , C_PROG_MUST TYPE TY_PFMENU VALUE 'IFC_MENU_PROG'
         , C_PARA_MUST TYPE TY_PFMENU VALUE 'IFC_MENU_PARA'
         , C_PRIC_MUST TYPE TY_PFMENU VALUE 'IFC_MENU_PRIC'
         , C_TIME_MUST TYPE TY_PFMENU VALUE 'IFC_MENU_TIME'
         , C_RELE_MUST TYPE TY_PFMENU VALUE 'IFC_RELE'
         , C_ACCP_MUST TYPE TY_PFMENU VALUE 'IFC_ACCEPT'
         , C_RMOD_MUST TYPE TY_PFMENU VALUE 'IFC_CHANGE_RELE'
         .

* Konstanten zur Navigation im Modulpool
TYPES: TY_OKCODE TYPE SYUCOMM.
CONSTANTS: C_BACK_CODE TYPE TY_OKCODE VALUE 'RTRN'
         , C_OKCD_CODE TYPE TY_OKCODE VALUE 'OK  '
         , C_SAVE_CODE TYPE TY_OKCODE VALUE 'SAVE'
         , C_END__CODE TYPE TY_OKCODE VALUE 'END '
         , C_BREA_CODE TYPE TY_OKCODE VALUE 'BREA'
         , C_MARK_CODE TYPE TY_OKCODE VALUE 'CS  '
         , C_HEAD_CODE TYPE TY_OKCODE VALUE 'HEAD'
         , C_VARI_CODE TYPE TY_OKCODE VALUE 'VARI'
         , C_PROG_CODE TYPE TY_OKCODE VALUE 'UC4 '
         , C_TIME_CODE TYPE TY_OKCODE VALUE 'TIME'
         , C_COPY_CODE TYPE TY_OKCODE VALUE 'COPY'
         , C_VERS_CODE TYPE TY_OKCODE VALUE 'IFVS'
         , C_DEFI_CODE TYPE TY_OKCODE VALUE 'PROG'
         , C_PRIC_CODE TYPE TY_OKCODE VALUE 'PRIC'
         , C_SWTM_CODE TYPE TY_OKCODE VALUE 'SWTM'
         , C_TRAN_CODE TYPE TY_OKCODE VALUE 'TRAN'
         , C_TRA2_CODE TYPE TY_OKCODE VALUE 'TRA2'
         , C_TRA3_CODE TYPE TY_OKCODE VALUE 'TRA3'
         , C_NEW__CODE TYPE TY_OKCODE VALUE 'NEW '
         , C_CATK_CODE TYPE TY_OKCODE VALUE 'CATK'
         , C_DOCU_CODE TYPE TY_OKCODE VALUE 'DOCU'
         , C_DOC2_CODE TYPE TY_OKCODE VALUE 'DOCU2'
         , C_DOC3_CODE TYPE TY_OKCODE VALUE 'DOCU3'
         , C_ADMI_CODE TYPE TY_OKCODE VALUE 'ADMI'
         , C_DELE_CODE TYPE TY_OKCODE VALUE 'DELE'
         , C_SELM_CODE TYPE TY_OKCODE VALUE 'SELM'
         , C_FIND_CODE TYPE TY_OKCODE VALUE 'FIND'
         , C_IFCF_CODE TYPE TY_OKCODE VALUE '%FCF'
         , C_LNEW_CODE TYPE TY_OKCODE VALUE 'L_NEW'
         , C_LDEL_CODE TYPE TY_OKCODE VALUE 'L_DEL'
         , C_RELE_CODE TYPE TY_OKCODE VALUE 'ACCP'
         , C_PMM__CODE TYPE TY_OKCODE VALUE 'P--'
         , C_PM___CODE TYPE TY_OKCODE VALUE 'P-'
         , C_PP___CODE TYPE TY_OKCODE VALUE 'P+'
         , C_PPP__CODE TYPE TY_OKCODE VALUE 'P++'
         , C_VDEL_CODE TYPE TY_OKCODE VALUE 'VDEL'
         , C_LEGE_CODE TYPE TY_OKCODE VALUE 'LEGE'
         , C_CHAN_CODE TYPE TY_OKCODE VALUE 'CHANGE'
         , C_RMOD_CODE TYPE TY_OKCODE VALUE 'RMOD'
         , C_PRIN_CODE TYPE TY_OKCODE VALUE '%PRI'
         , C_ADHOC_CODE TYPE TY_OKCODE VALUE 'ADHOC'
         .

* Dynpros
TYPES: TY_DYNPRO TYPE SYDYNNR.
CONSTANTS: C_MAIN_DYNP TYPE TY_DYNPRO VALUE '1000'
         , C_HEAD_DYNP TYPE TY_DYNPRO VALUE '1001'
         , C_VARI_DYNP TYPE TY_DYNPRO VALUE '1002'
         , C_PROG_DYNP TYPE TY_DYNPRO VALUE '1003'
         , C_DEFI_DYNP TYPE TY_DYNPRO VALUE '1004'
         , C_TIME_DYNP TYPE TY_DYNPRO VALUE '1005'
         , C_1006_DYNP TYPE TY_DYNPRO VALUE '1006'
         , C_1007_DYNP TYPE TY_DYNPRO VALUE '1007'
*         , c_titl_sdyn type ty_dynpro value '0100'
         , C_TITL_SDYN TYPE TY_DYNPRO VALUE '0101'
         , C_TCTL_SDYN TYPE TY_DYNPRO VALUE '0200'
         , C_TCTV_SDYN TYPE TY_DYNPRO VALUE '0300'
         , C_MTRX_SDYN TYPE TY_DYNPRO VALUE '0400'
         , C_RELE_SDYN TYPE TY_DYNPRO VALUE '0500'
         , C_FREI_SDYN TYPE TY_DYNPRO VALUE '2000'
         , C_ADHOC_SDYN TYPE TY_DYNPRO VALUE '2500'
         , C_ACCP_SDYN TYPE TY_DYNPRO VALUE '3000'
         , C_RMOD_SDYN TYPE TY_DYNPRO VALUE '4000'
         , C_MODR_SDYN TYPE TY_DYNPRO VALUE '4001'
         .

* Unterscheidung zwischen einer "alten" nicht aktuellen Version
* und einer neuen, in der die Details sich ändern dürfen.
TYPES: TY_IFVERS TYPE C.
CONSTANTS: C_IOLD_VERS TYPE TY_IFVERS VALUE 'O'
         , C_INEW_VERS TYPE TY_IFVERS VALUE 'N'
         .

TYPES: TY_STATUS(2) TYPE N.
CONSTANTS: C_1000_STAT TYPE TY_STATUS VALUE '01'   " Einstiegsbild
         , C_1001_STAT TYPE TY_STATUS VALUE '02'   " Kopfdaten
         , C_1002_STAT TYPE TY_STATUS VALUE '04'   " Varianten
         , C_1003_STAT TYPE TY_STATUS VALUE '03'   " Program
         , C_1004_STAT TYPE TY_STATUS VALUE '05'   " Spezifikation
         , C_2000_STAT TYPE TY_STATUS VALUE '06'
         , C_2500_STAT TYPE TY_STATUS VALUE '14'
         , C_3000_STAT TYPE TY_STATUS VALUE '07'   " Abnahme
         , C_4000_STAT TYPE TY_STATUS VALUE '08'
         , C_4001_STAT TYPE TY_STATUS VALUE '09'
         , C_1005_STAT TYPE TY_STATUS VALUE '10'
         , C_1006_STAT TYPE TY_STATUS VALUE '05'
         , C_1007_STAT TYPE TY_STATUS VALUE '12'
         , C_DOCU_STAT TYPE TY_STATUS VALUE '11'
         , C_PRIC_STAT TYPE TY_STATUS VALUE '13'
         .

TYPES: TY_CALLM TYPE XFLAG.
CONSTANTS: C_SETS_CALLM TYPE TY_CALLM VALUE SPACE   " Call screen
         , C_CALS_CALLM TYPE TY_CALLM VALUE 'X'     " Set screen
         .

TYPES: TY_TRANM TYPE I.
CONSTANTS: C_TRAN_TRANM TYPE TY_TRANM VALUE '1'  " Transport values
         , C_TRA2_TRANM TYPE TY_TRANM VALUE '2'  " Delete entries
         , C_TRA3_TRANM TYPE TY_TRANM VALUE '3'  " Show transport
         .

TYPES: BEGIN OF TY_EXCMD
     , FUNC TYPE GUI_CODE
     , END OF TY_EXCMD
     , TY_T_EXCMD TYPE STANDARD TABLE OF TY_EXCMD INITIAL SIZE 0.

TYPES: TY_TABLIX TYPE /SIE/HR_IDP_DB_SEL.

*CONSTANTS: C_ALL_TABL TYPE TY_TABLIX VALUE 'XXXXXXXXXXXXX'.
CONSTANTS: C_ALL_TABL TYPE TY_TABLIX VALUE 'XXXXXXXXXXXXXX'. "SIE001

TYPES: TY_ACTIVITY TYPE /SIE/HR_IDP_ACTIVITY.
CONSTANTS:  C_DISPLAY      TYPE TY_ACTIVITY VALUE '00'
          , C_CREATE      TYPE TY_ACTIVITY        VALUE '10'
          , C_UPDATE       TYPE TY_ACTIVITY       VALUE '20'
          , C_DELETE            TYPE TY_ACTIVITY  VALUE '30'
          , C_RELEASE        TYPE TY_ACTIVITY     VALUE '40'
          , C_CONFIRM         TYPE TY_ACTIVITY    VALUE '50'
          , C_UTILITY         TYPE TY_ACTIVITY    VALUE '60'
          , C_CREATE_EXE        TYPE TY_ACTIVITY  VALUE '70'
          , C_CREATE_EXE_T    TYPE TY_ACTIVITY VALUE '71'
          , C_DELETE_EXE        TYPE TY_ACTIVITY  VALUE '80'
          , C_DISPLAY_EXE       TYPE TY_ACTIVITY  VALUE '90'
          .

* Hilfstabelle um Parameter zu parsen
TYPES: TY_PARAM TYPE /SIE/HR_IDP_PARAMETER.

CONSTANTS: C_SEMICOLON    TYPE C VALUE ';',
           C_CONSTANT(11) TYPE C VALUE 'C_KONSTANTE'.      "SIE001

TYPES: BEGIN OF TY_PAIR
     , VARIABLE TYPE /SIE/HR_IDP_KONVPARA
     , VALUE TYPE /SIE/HR_IDP_KONVPARA
     , END OF TY_PAIR
     , TY_TPAIR TYPE STANDARD TABLE OF TY_PAIR
     .
