PROCESS BEFORE OUTPUT.
 MODULE INIT_2000.
 MODULE READ_2000.
 MODULE READ_S1LT.
 MODULE SET_STATUS.
*
PROCESS AFTER INPUT.
 MODULE EXIT_2000 AT EXIT-COMMAND.
 CHAIN.
  FIELD /SIE/HR_IDP_S1-IFCID.
 ENDCHAIN.
 MODULE COPY_OK_CODE.
 FIELD /SIE/HR_IDP_S1-IFCID SELECT * FROM /SIE/HR_IDP_S1
                            WHERE IFCID = /SIE/HR_IDP_S1-IFCID
                            WHENEVER NOT FOUND SEND ERRORMESSAGE 304.
 MODULE USER_COMMAND_2000.
