*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /SIE/LHR_IEMPKENZTOP.              " Global Data
  INCLUDE /SIE/LHR_IEMPKENZUXX.              " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /SIE/LHR_IEMPKENZF00                    . " subprograms
  INCLUDE /SIE/LHR_IEMPKENZI00                    . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /SIE/LHR_IEMPKENZF...              " Subprograms
* INCLUDE /SIE/LHR_IEMPKENZO...              " PBO-Modules
* INCLUDE /SIE/LHR_IEMPKENZI...              " PAI-Modules
