*----------------------------------------------------------------------*
*   INCLUDE /SIE/HR_IDP_IFC_FIND_DATA                                  *
*----------------------------------------------------------------------*

INCLUDE /SIE/HR_IDP_TYPES.
TYPE-POOLS: SLIS.

TABLES: /SIE/HR_IDP_S1
      , /SIE/HR_IDP_S1T
      , /SIE/HR_IDP_S1LT
      , /SIE/HR_IDP_S1VN
      , /SIE/HR_IDP_S1PG
      , /SIE/HR_IDP_S1R
      , /SIE/HR_IDP_F1
      , /SIE/HR_IDP_F1T
      ,  /SIE/HR_IDP_F1LT
      , /SIE/HR_IDP_FIELDSEARCH
      .

DATA: G_VS1T TYPE STANDARD TABLE OF /SIE/HR_IDP_VS1T
    , G_DATA TYPE STANDARD TABLE OF /SIE/HR_IDP_IFCSEARCH
    , G_WA TYPE /SIE/HR_IDP_IFCSEARCH
    .

* Listaufbereitung
DATA:   GT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV.
DATA:   GT_OUTTAB LIKE SIMLISTRUC OCCURS 0 WITH HEADER LINE.
DATA:   G_TABNAME TYPE SLIS_TABNAME VALUE 'G_DATA'.
DATA:   G_REPID LIKE SY-REPID.
DATA    G_STATUS TYPE SLIS_FORMNAME VALUE 'STANDARD_02'.
DATA    GS_LAYOUT TYPE SLIS_LAYOUT_ALV.
DATA    G_USER_COMMAND TYPE SLIS_FORMNAME VALUE 'USER_COMMAND'.
DATA    G_SAVE(1) TYPE C.
DATA    G_VARIANT LIKE DISVARIANT.
