PROCESS BEFORE OUTPUT.
 MODULE SET_TRAN_STATUS_1003.
 MODULE INIT.                               " Wird von allen aufgerufen
 MODULE SET_STATUS.                         " Wird von allen aufgerufen
  CALL SUBSCREEN SUBSCR_TITLE INCLUDING '/SIE/HR_IDP_IFC' C_TITL_SDYN.
  MODULE READ_S1LT.
  MODULE READ_S1VN.
  MODULE READ_S1DF.
  MODULE READ_S1F.
* ....HIER KOMMEN DIE ÄNDERUNGEN
 MODULE READ_1003.
 MODULE SET_SUB_D1003.
 CALL SUBSCREEN UC4_REF1 INCLUDING '/SIE/HR_IDP_IFC' DYNPRONR.
 MODULE MODIFY_SCREEN.
* module modify_checkboxes.
* module fill_defaults_1003.


PROCESS AFTER INPUT.
 MODULE EXIT_COMMAND AT EXIT-COMMAND.       " Wird von allen aufgerufen
 MODULE COPY_OK_CODE.                       " Wird von allen aufgerufen
 CHAIN.
 FIELD:
  /SIE/HR_IDP_S1DF-PROGR,
  /SIE/HR_IDP_S1DF-VARIA,
  /SIE/HR_IDP_S1DF-GNRTD,
  /SIE/HR_IDP_S1DF-GNRVT,
  /SIE/HR_IDP_S1DF-UC4NM.
 ENDCHAIN.
 CHAIN.
 FIELD:
  /SIE/HR_IDP_S1DF-PROGR,
  /SIE/HR_IDP_S1DF-VARIA,
  /SIE/HR_IDP_S1DF-GNRTD,
  /SIE/HR_IDP_S1DF-GNRVT.
  MODULE CHECK_PROGR ON CHAIN-REQUEST.
 ENDCHAIN.
 CHAIN.
 FIELD /SIE/HR_IDP_S1DF-UC4NM.
 MODULE CHECK_BNAME.
 ENDCHAIN.
CHAIN.
FIELD: /SIE/HR_IDP_S1DF-PROGR,
/SIE/HR_IDP_S1DF-VARIA,
/SIE/HR_IDP_S1DF-GNRTD,
/SIE/HR_IDP_S1DF-GNRVT.
MODULE CHECK_PROGRAM.
ENDCHAIN.

 CALL SUBSCREEN SUBSCR_TITLE.
* ....HIER KOMMEN DIE ÄNDERUNGEN
 CALL SUBSCREEN UC4_REF1.
 MODULE WRITE_1003.
 MODULE SET_SUB_1003.
 MODULE USER_COMMAND.                       " Wird von allen aufgerufen
















