FUNCTION /SIE/HR_IDP_IFC_POPUP_TEXT.
*"----------------------------------------------------------------------
*"*"Lokale Schnittstelle:
*"       IMPORTING
*"             VALUE(TITEL)
*"             VALUE(START_COLUMN) LIKE  SY-CUCOL DEFAULT 1
*"             VALUE(START_ROW) LIKE  SY-CUROW DEFAULT 1
*"             VALUE(END_COLUMN) LIKE  SY-CUCOL DEFAULT 5
*"             VALUE(END_ROW) LIKE  SY-CUROW DEFAULT 0
*"             VALUE(INFOFLAG) DEFAULT SPACE
*"       EXPORTING
*"             VALUE(ANSWER)
*"       TABLES
*"              LINES STRUCTURE  POPUPTEXT
*"----------------------------------------------------------------------
DATA COLUMNS LIKE SY-CUCOL.
DATA ROWS    LIKE SY-CUROW.
DATA CROW LIKE SY-CUROW.
DATA HROW LIKE SY-CUROW.
DATA CCOL LIKE SY-CUCOL.
DATA MCOL LIKE SY-CUCOL.
INFOFLAG = INFOFLAG.
COLUMNS = END_COLUMN - START_COLUMN + 1.
ROWS    = END_ROW    - START_ROW    + 1.
SPOP-TITEL = TITEL.
REFRESH LINESH.  REFRESH LINESB.
LOOP AT LINES.
     CROW = CROW + 1.
     IF LINES-TOPOFPAGE NE SPACE.
        HROW = HROW + 1.
        CCOL = STRLEN( LINES-TEXT ).
        LINESH = LINES. APPEND LINESH.
     ELSE.
        IF HROW > 0.
           CCOL = STRLEN( LINES-TEXT ) + 2.
        ELSE.
           CCOL = STRLEN( LINES-TEXT ).
        ENDIF.
        LINESB = LINES. APPEND LINESB.
     ENDIF.
     IF CCOL > COLUMNS. COLUMNS = CCOL. ENDIF.
ENDLOOP.
NCOL = COLUMNS.
END_COLUMN = START_COLUMN + COLUMNS - 1.
IF HROW > 0. CROW = CROW + 2. ENDIF.
IF END_ROW = 0.
   END_ROW = START_ROW + CROW - 1.
*  IF ROWS < 4. ROWS = ROWS + 1. ENDIF.
ENDIF.

CALL SCREEN 40 STARTING AT START_COLUMN START_ROW
                 ENDING AT END_COLUMN   END_ROW.
IF SY-UCOMM EQ 'BACK'.
   ANSWER = 'Y'.
ELSEIF SY-UCOMM EQ 'INFO'.
   ANSWER = 'I'.
ELSE.
   ANSWER = 'N'.
ENDIF.
ENDFUNCTION.
