PROCESS BEFORE OUTPUT.
 MODULE INIT_0600.
 MODULE SET_PF_STATUS_103.
 MODULE IFCID_READ.
*
PROCESS AFTER INPUT.
 MODULE EXIT_COMMAND_0600 AT EXIT-COMMAND.
 CHAIN.
   FIELD:  /SIE/HR_IDP_COPY_FIELDS-IFCID
         , /SIE/HR_IDP_COPY_FIELDS-NEW_IFCID
         , /SIE/HR_IDP_COPY_FIELDS-VRSNR
         .
 ENDCHAIN.
 MODULE COPY_OK_CODE.
 CHAIN.
 FIELD: /SIE/HR_IDP_COPY_FIELDS-IFCID
      , /SIE/HR_IDP_COPY_FIELDS-NEW_IFCID
      .
       MODULE CHECK_INPUT_600.
 ENDCHAIN.
 MODULE USER_COMMAND_0600.
