FUNCTION-POOL /SIE/HR_IDP_F4 MESSAGE-ID /SIE/HR_IDP_MESSAGES.

INCLUDE <ICON>.

TYPE-POOLS SHLP.

* Konstanten (werden benötigt im FB /SIE/HR_IDP_F4_GET_IDENT)
*types: ty_trcode type sytcode.
*constants: c_disp_tcod type ty_trcode value '/SIE/HR_IDP_IFC_DISP'
*         , c_modi_tcod type ty_trcode value '/SIE/HR_IDP_IFC_MOD'
*         .

* Datendefinitionen für das Control
INCLUDE <CTLDEF>.
INCLUDE CNT4DEFS.

INCLUDE /SIE/HR_IDP_TYPES.

TYPES: NODE_TABLE_TYPE LIKE STANDARD TABLE OF TREEV_NODE
         WITH DEFAULT KEY.

TYPES: ITEM_TABLE_TYPE LIKE STANDARD TABLE OF /SIE/HR_IDP_F4
       WITH DEFAULT KEY.


DATA: TREE TYPE CNTL_HANDLE,  " Handle of the Tree Control
      TREE_CONTROL_CREATED TYPE C,
      OK_CODE LIKE SY-UCOMM,
      G_ITAB_FIELDS TYPE STANDARD TABLE OF /SIE/HR_IDP_FNAME
                    INITIAL SIZE 0.


DATA: G_SEL_FIELDS TYPE STANDARD TABLE OF /SIE/HR_IDP_F4_SEL_FIELDS
      INITIAL SIZE 0 WITH HEADER LINE.


DATA:  G_GRTYPE TYPE /SIE/HR_IDP_GRKEY
    , G_DISPLAY TYPE XFLAG
    , G_HDFT TYPE XFLAG
    , WA_COMMAND TYPE TY_EXCMD
    , G_COMMAND TYPE TY_T_EXCMD
    .

* fields on dynpro 1000
DATA: G_EVENT(15),
*      g_node_key like treev_node-node_key.
       G_NODE_KEY LIKE TREEV_HDR-NAME.

* application data
TABLES: /SIE/HR_IDP_F0
      , /SIE/HR_IDP_F0T
      , /SIE/HR_IDP_F1
      , /SIE/HR_IDP_F1T
      .
DATA: G_ITAB_F0 TYPE STANDARD TABLE OF /SIE/HR_IDP_F0 INITIAL SIZE 0
      WITH HEADER LINE
    , G_WORK_F0 TYPE /SIE/HR_IDP_F0
.

TYPES: BEGIN OF UI_STRUCT.
TYPES: NODEID TYPE SEU_ID.
TYPES: PREDID TYPE SEU_ID.
        INCLUDE STRUCTURE /SIE/HR_IDP_F0.
TYPES: TEXT LIKE /SIE/HR_IDP_F0T-IDENT.
TYPES: END OF UI_STRUCT,
       UI_TABLE TYPE UI_STRUCT OCCURS 0.

* tree data
DATA: UI_TREE LIKE SNODETEXT OCCURS 0 WITH HEADER LINE
    , UI TYPE UI_STRUCT OCCURS 0 WITH HEADER LINE
    , UI_H TYPE UI_STRUCT OCCURS 0 WITH HEADER LINE
    .

DATA: TREELIST TYPE STANDARD TABLE OF SNODETEXT INITIAL SIZE 0.

DATA: IDX TYPE N VALUE '0'.

* Daten zur Navigation und Selektion der Zeilen
DATA SELECTED_VALUE TYPE SEUCOMM-NAME.

DATA: OKCODE LIKE SY-UCOMM
    , SVCODE LIKE SY-UCOMM
    .

TABLES: /SIE/HR_IDP_F4_QFELDER
      , /SIE/HR_IDP_F1LT
      .


DATA: G_ITEMS TYPE ITEM_TABLE_TYPE
    , WA_ITEMS LIKE /SIE/HR_IDP_F4
    .

DATA: G_KZHDFT TYPE TY_YESNO,
      OLD_KZHDFT TYPE TY_YESNO.
DATA: G_RC TYPE SYSUBRC.
